function tests = test_independent_full_fault_reservoir_export
%TEST_INDEPENDENT_FULL_FAULT_RESERVOIR_EXPORT Revised MAT contract test.
tests = functiontests(localfunctions);
end


function setupOnce(testCase)
testDir = fileparts(mfilename('fullpath'));
addpath(fileparts(testDir));
testCase.TestData.outputDir = string(tempname);
mkdir(testCase.TestData.outputDir);
end


function teardownOnce(testCase)
if isfolder(testCase.TestData.outputDir)
    rmdir(testCase.TestData.outputDir, 's');
end
end


function testRevisedSchemaAndProvenance(testCase)
[pc, kr, selection, porosity, fieldPerm] = revisedFixture();
replayManifest = fullfile(testCase.TestData.outputDir, ...
    'replay_manifest.csv');
writetable(table((1:10)', 'VariableNames', {'ReplaySourceRow'}), ...
    replayManifest);

methodHash = repmat('f', 1, 64);
outputs = export_reservoir_ready_pc_kr_cases( ...
    pc, kr, selection, testCase.TestData.outputDir, ...
    'PorosityInput', porosity, ...
    'PermeabilityInput', fieldPerm, ...
    'ExpectedWindowCount', 2, ...
    'ExpectedSliceCount', 5, ...
    'ReplayManifestInput', replayManifest, ...
    'ProductionMethodConfigHash', methodHash);

verifyEqual(testCase, numel(outputs.matFiles), 1);
loaded = load(outputs.matFiles(1), 'reservoirReady');
R = loaded.reservoirReady;
verifyEqual(testCase, string(R.schemaVersion), "1.7");
verifyEqual(testCase, string(R.caseType), "independent_full");
verifyTrue(testCase, logical(R.useForProbabilisticUq));
verifyFalse(testCase, logical(R.isBenchmark));
verifyFalse(testCase, logical(R.isStressTest));
verifySize(testCase, R.predictRealizationIdMap, [2, 5]);
verifySize(testCase, R.windowSliceMap.windowId, [2, 5]);
verifySize(testCase, R.windowSliceMap.sliceId, [2, 5]);
verifySize(testCase, R.Kxx_mD, [2, 5]);
verifySize(testCase, R.Kyy_mD, [2, 5]);
verifySize(testCase, R.Kzz_mD, [2, 5]);
verifySize(testCase, R.effectivePorosity, [2, 5]);
verifySize(testCase, R.SwiEff, [2, 5]);
verifyEqual(testCase, R.SwiEff, 0.3 .* ones(2, 5), ...
    'AbsTol', 1.0e-14);
verifyEqual(testCase, string(R.configurationHash), string(methodHash));
verifyEqual(testCase, strlength(string(R.replayManifestHash)), 64);
verifyEqual(testCase, strlength(string(R.samplingManifestHash)), 64);
verifyTrue(testCase, ...
    logical(R.effectivePermeability.assignmentMetadataExplicit));
verifyEqual(testCase, ...
    string(R.effectivePermeability.coordinateContract. ...
        downstream_transform_contract), ...
    "fault_local_to_reservoir_grid_signed_yz_v1");
verifyEqual(testCase, double(R.saturationRegions.regionCount), 10);
verifyTrue(testCase, logical(R.saturationRegions.validation.passed));
qa = outputs.qaTable;
verifyEqual(testCase, string(qa.SchemaVersion), "1.7");
verifyEqual(testCase, string(qa.CaseType), "independent_full");
verifyTrue(testCase, logical(qa.UseForProbabilisticUq));
verifyTrue(testCase, logical(qa.AssignmentMetadataExplicit));
verifyEqual(testCase, string(qa.ConfigurationHash), string(methodHash));
verifyEqual(testCase, strlength(string(qa.SamplingManifestHash)), 64);
verifyEqual(testCase, strlength(string(qa.ReplayManifestHash)), 64);
verifyEqual(testCase, string(qa.CoordinateTransformContract), ...
    "fault_local_to_reservoir_grid_signed_yz_v1");
end


function [pc, kr, selection, porosity, fieldPerm] = revisedFixture()
geologyId = "g001";
caseId = 1;
caseName = "Independent full 001";
windows = ["famp1"; "famp2"];
nWindows = numel(windows);
nSlices = 5;

pcRows = cell(nWindows * nSlices * 2, 14);
krRows = cell(nWindows * nSlices * 2, 15);
porosityRows = cell(nWindows * nSlices, 10);
selectionRows = cell(nWindows, 6);
pcRow = 0;
krRow = 0;
phiRow = 0;

for w = 1:nWindows
    representativeRow = 100 * w + 1;
    selectionRows(w, :) = {geologyId, caseId, caseName, windows(w), ...
        representativeRow, 0.3};
    for s = 1:nSlices
        replaySource = 100 * w + s;
        selectedSample = 10 * w + s;
        replaySeed = 1000 * w + s;
        phiRow = phiRow + 1;
        porosityRows(phiRow, :) = {replaySource, geologyId, caseId, ...
            caseName, windows(w), s, 0.25, 1.0, 0.25, true};
        for point = 1:2
            pcRow = pcRow + 1;
            gasSaturation = (point - 1) * 0.7;
            pcBar = [0.1, 10.0];
            pcRows(pcRow, :) = {replaySource, geologyId, caseId, ...
                caseName, windows(w), s, gasSaturation, pcBar(point), ...
                0.7, 0.3, "independent", "full_distribution", ...
                selectedSample, replaySeed};

            krRow = krRow + 1;
            normalizedSg = point - 1;
            krRows(krRow, :) = {replaySource, geologyId, caseId, ...
                caseName, windows(w), s, windows(w) + "_shape", ...
                representativeRow, 0.3, 0.7, normalizedSg, ...
                gasSaturation, 1.0 - gasSaturation, ...
                normalizedSg, 1.0 - normalizedSg};
        end
    end
end

pc = cell2table(pcRows, 'VariableNames', { ...
    'ReplaySourceRow', 'GeologyId', 'Level3CaseId', 'Level3CaseName', ...
    'Window', 'SliceIndex', 'GasSaturation', 'PcBar', 'BulkSgMax', ...
    'EffectiveSwi', 'AssignedState', 'SamplingPool', ...
    'SelectedSampleIndex', 'ReplaySeed'});
kr = cell2table(krRows, 'VariableNames', { ...
    'PcReplaySourceRow', 'GeologyId', 'Level3CaseId', ...
    'Level3CaseName', 'Window', 'SliceIndex', 'ShapeId', ...
    'RepresentativeKrReplaySourceRow', 'EffectiveSwi', 'BulkSgMax', ...
    'NormalizedSg', 'GasSaturation', 'WaterSaturation', 'Krg', 'Krw'});
selection = cell2table(selectionRows, 'VariableNames', { ...
    'GeologyId', 'Level3CaseId', 'Level3CaseName', 'Window', ...
    'SelectedReplaySourceRow', 'SelectedEffectiveSwi'});
porosity = cell2table(porosityRows, 'VariableNames', { ...
    'ReplaySourceRow', 'GeologyId', 'Level3CaseId', 'Level3CaseName', ...
    'Window', 'SliceIndex', 'PoreVolume', 'BulkVolume', ...
    'UpscaledPorosity', 'Passed'});

fieldPerm = revisedFieldPermFixture(geologyId, caseId, windows, nSlices);
end


function fieldPerm = revisedFieldPermFixture( ...
        geologyId, caseId, windows, nSlices)
nWindows = numel(windows);
components = ["kxx"; "kyy"; "kzz"];
perm = nan(1, 1, nSlices, nWindows, 3);
selected = zeros(1, 1, nSlices, nWindows, 'int64');
realization = zeros(1, 1, nSlices, nWindows, 'int64');
replaySeed = zeros(1, 1, nSlices, nWindows, 'int64');
for w = 1:nWindows
    for s = 1:nSlices
        perm(1, 1, s, w, :) = [1 + w + s, 2 + w + s, 3 + w + s];
        selected(1, 1, s, w) = 10 * w + s;
        realization(1, 1, s, w) = 100 * w + s;
        replaySeed(1, 1, s, w) = 1000 * w + s;
    end
end

hashA = repmat('a', 1, 64);
hashB = repmat('b', 1, 64);
hashC = repmat('c', 1, 64);
fieldPerm = struct( ...
    'geology_id', geologyId, ...
    'level3_case_id', caseId, ...
    'slice_index', (1:nSlices)', ...
    'window', windows, ...
    'component', components, ...
    'perm', perm, ...
    'logK', log10(perm), ...
    'selected_sample_index', selected, ...
    'predict_realization_id', realization, ...
    'exact_replay_seed', replaySeed, ...
    'sampling_seed', reshape(int64([12345, 67890]), [1, 1, nWindows]), ...
    'checkpoint_sha256', {{hashA, hashB}}, ...
    'checkpoint_relative_path', {{'g001/famp1.mat', 'g001/famp2.mat'}}, ...
    'source_checkpoint_file', {{'famp1.mat', 'famp2.mat'}}, ...
    'assigned_state', reshape(["independent", "independent"], ...
        [1, 1, nWindows]), ...
    'sampling_pool', reshape(["full_distribution", "full_distribution"], ...
        [1, 1, nWindows]), ...
    'sampling_case_id', "G001_IND_001", ...
    'phase', "phase1", ...
    'case_type', "independent_full", ...
    'replicate_id', int64(1), ...
    'use_for_probabilistic_uq', true, ...
    'is_benchmark', false, ...
    'is_stress_test', false, ...
    'sampling_manifest_sha256', hashA, ...
    'sampling_method_config_hash', hashB, ...
    'sampling_code_commit', repmat('1', 1, 40), ...
    'predict_method_config_hash', hashC, ...
    'predict_code_commit', repmat('2', 1, 40), ...
    'coordinate_contract', coordinateContractFixture());
end


function contract = coordinateContractFixture()
contract = struct( ...
    'schema_version', "fault_local_coordinate_contract_v1", ...
    'stored_coordinate_system', "PREDICT fault-local orthonormal axes", ...
    'component_labels', ["kxx"; "kyy"; "kzz"], ...
    'component_meanings', ["fault_normal"; "along_strike"; "down_dip"], ...
    'reservoir_coordinate_system', "reservoir-grid Cartesian axes", ...
    'rotation_required', true, ...
    'downstream_transform_contract', ...
        "fault_local_to_reservoir_grid_signed_yz_v1", ...
    'pre_rotated', false, ...
    'tensor_formula', ...
        "K_global = R * diag(K_local) * transpose(R)", ...
    'component_formula', "documented component mapping", ...
    'geometry_dependency', "one signed angle per fault cell");
end
