% Run the W6 collapsed-sand diagnostic sensitivity test.
%
% Before running:
%   1. Sync this repository on the Windows desktop that has MATLAB/MRST.
%   2. Start MATLAB.
%   3. Run MRST startup.m if MRST is not already on the MATLAB path.
%   4. From this repository, run this script or paste the command below.

outputDir = 'D:\codex_gom\w6_collapsed_sand_sensitivity';

results = gom_w6_collapsed_sand_sensitivity(outputDir, ...
    'Nsim', 2000, ...
    'FaultingDepth', 1000, ...
    'SandVcl', 0.1, ...
    'ClayVcl', 0.4, ...
    'UseParallel', true, ...
    'NumWorkers', 16, ...
    'Resume', true, ...
    'ShowProgress', true);

disp(results.summary)
