%RUN_REPLAY_SELECTED_PREDICT_REALIZATIONS Example calls for replay/export.
%
% This script demonstrates how to reproduce selected Level-3 PREDICT
% realizations and export fine-scale porosity/permeability fields. It does
% not modify the existing 2000-realization PREDICT libraries.
%
% Before running:
%   1. Start MATLAB from the repository or add this examples folder.
%   2. Run MRST startup.m on the machine where MRST is installed.
%   3. Make sure the three-level sampling summary CSV exists.

examplesDir = fileparts(mfilename('fullpath'));

selectionCsv = fullfile('D:', 'codex_gom', 'UQ_workflow', ...
    'three_level_sampling_162', 'summary', ...
    'level3_selected_vector_provenance_and_replay_status.csv');

outputDir = fullfile(examplesDir, 'results', 'selected_predict_replay');

%% Example 1: replay one complete six-window legacy/random pilot case.
% P1 in the pilot set: maximum-conduit strong fault-wide high.
% This exports W1-W6, one MAT file per window.
summaryP1 = replay_selected_predict_realizations( ...
    selectionCsv, outputDir, ...
    'DataRoot', fullfile(examplesDir, 'thickness_scenario_data'), ...
    'GeologyIds', {'s03_c001'}, ...
    'CaseLabels', {'case_001_zf0050_svcl010_cvcl040'}, ...
    'Level3CaseIds', 4, ...
    'MaxRows', 6);

disp(summaryP1)

%% Example 2: replay only one selected window realization.
% Uncomment and edit RowIndices after checking the provenance CSV.
% summaryOne = replay_selected_predict_realizations( ...
%     selectionCsv, outputDir, ...
%     'RowIndices', 1, ...
%     'MaxRows', 1);
%
% disp(summaryOne)

%% Example 3: replay a single window from a selected case.
% Uncomment to export only W6 from the same P1 case.
% summaryW6 = replay_selected_predict_realizations( ...
%     selectionCsv, outputDir, ...
%     'GeologyIds', {'s03_c001'}, ...
%     'CaseLabels', {'case_001_zf0050_svcl010_cvcl040'}, ...
%     'Level3CaseIds', 4, ...
%     'Windows', {'famp6'}, ...
%     'MaxRows', 1);
%
% disp(summaryW6)

%% Example 4: replay collapsed + cell_union_psmear data.
% Use this after creating a Level-3 selection/provenance CSV that points to
% the collapsed-cell-union PREDICT libraries. In auto mode, the replay
% utility reads SmearOverlapRule and CollapseAdjacentLithology from the
% production metadata.
%
% collapsedDataRoot = fullfile(examplesDir, ...
%     'thickness_scenario_data_collapsed_cell_union');
% collapsedSelectionCsv = fullfile('D:', 'codex_gom', 'UQ_workflow', ...
%     'three_level_sampling_162_collapsed_cell_union', 'summary', ...
%     'level3_selected_vector_provenance_and_replay_status.csv');
% summaryCollapsed = replay_selected_predict_realizations( ...
%     collapsedSelectionCsv, outputDir, ...
%     'DataRoot', collapsedDataRoot, ...
%     'MaxRows', 6);
%
% disp(summaryCollapsed)
