function outputs = export_reservoir_ready_pc_kr_cases( ...
        pcNativeInput, krSliceInput, selectionInput, outputDir, varargin)
%EXPORT_RESERVOIR_READY_PC_KR_CASES Validate and package fault-cell inputs.
%
%   OUTPUTS = EXPORT_RESERVOIR_READY_PC_KR_CASES(PCNATIVEINPUT,
%   KRSLICEINPUT, SELECTIONINPUT, OUTPUTDIR) accepts either tables or CSV
%   paths. POROSITYINPUT is supplied as a name-value option and contains
%   the volume-weighted porosity summary from Pc replay. PERMEABILITYINPUT
%   is the canonical texas_field_sampling_compact.mat file (or its
%   fieldPerm struct). For every geology/case combination the function:
%     1. verifies complete window and slice coverage;
%     2. imports kxx, kyy, and kzz from the canonical permeability array;
%     3. verifies PREDICT sample indices and replay seeds against Pc;
%     4. verifies one physical upscaled porosity per fault cell;
%     5. verifies that Pc and Kr use identical slice-specific Swi endpoints;
%     6. checks Pc/Kr monotonicity and physical Kr bounds;
%     7. verifies one Swi-medoid representative per window; and
%     8. writes one self-contained reservoir-ready MAT file plus a QA CSV.
%
%   Pc curves remain slice specific. Kr curves use one normalized dynamic
%   shape per window, mapped to each slice's own Pc-derived BulkSgMax. The
%   optional full-Pc-curve medoids are not consumed here.
%
%   Name-value options:
%     PorosityInput       required table or CSV path
%     PermeabilityInput   required fieldPerm struct or compact MAT path
%     ExpectedWindowCount  default 6
%     ExpectedSliceCount   default 87
%     EndpointTolerance    default 1e-10
%     MonotonicTolerance   default 1e-8
%     PorosityTolerance    default 1e-12
%     PermeabilityTolerance default 2e-3 log10 units. This allows only the
%                           known eight-decimal CSV serialization difference
%                           between independently stored perm and logK values.
%     ReplayManifestInput   optional replay-manifest CSV path. Its SHA-256
%                           is embedded in revised-design outputs.
%     ProductionMethodConfigHash optional SHA-256 of the frozen production
%                           replay/Pc/Kr configuration.

%   The MAT schema is intentionally independent of MRST so a reservoir
%   model can load and map the checked curves without rerunning upscaling.

p = inputParser;
addParameter(p, 'PorosityInput', [], ...
    @(x) isempty(x) || istable(x) || ischar(x) || isstring(x));
addParameter(p, 'PermeabilityInput', [], ...
    @(x) isempty(x) || isstruct(x) || ischar(x) || isstring(x));
addParameter(p, 'ExpectedWindowCount', 6, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'ExpectedSliceCount', 87, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'EndpointTolerance', 1.0e-10, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'MonotonicTolerance', 1.0e-8, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'PorosityTolerance', 1.0e-12, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'PermeabilityTolerance', 2.0e-3, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'ReplayManifestInput', "", ...
    @(x) ischar(x) || isstring(x));
addParameter(p, 'ProductionMethodConfigHash', "", ...
    @(x) ischar(x) || isstring(x));
parse(p, varargin{:});
opt = p.Results;
assert(~isempty(opt.PorosityInput), 'ReservoirReady:MissingPorosityInput', ...
    ['PorosityInput is required so every reservoir fault cell receives ', ...
     'an upscaled porosity.']);
assert(~isempty(opt.PermeabilityInput), ...
    'ReservoirReady:MissingPermeabilityInput', ...
    ['PermeabilityInput is required so every reservoir fault cell ', ...
     'receives canonical kxx, kyy, and kzz values.']);

[pc, pcSource] = loadInputTable(pcNativeInput, 'native Pc');
[kr, krSource] = loadInputTable(krSliceInput, 'slice Kr');
[selection, selectionSource] = loadInputTable(selectionInput, ...
    'Swi-medoid selection');
[porosity, porositySource] = loadInputTable(opt.PorosityInput, ...
    'upscaled porosity');
[fieldPerm, permeabilitySource] = loadPermeabilityInput( ...
    opt.PermeabilityInput);
replayManifestSource = string(opt.ReplayManifestInput);
productionMethodConfigHash = lower(strtrim(string( ...
    opt.ProductionMethodConfigHash)));
if replayManifestSource ~= ""
    assert(isscalar(replayManifestSource) && isfile(replayManifestSource), ...
        'ReservoirReady:MissingReplayManifest', ...
        'Replay manifest input not found: %s', replayManifestSource);
    replayManifestSha256 = sha256File(replayManifestSource);
else
    replayManifestSha256 = "";
end
if productionMethodConfigHash ~= ""
    assert(isSha256(productionMethodConfigHash), ...
        'ReservoirReady:ProductionConfigHash', ...
        'ProductionMethodConfigHash must be a 64-character SHA-256 value.');
end
ensureFolder(outputDir);

requireColumns(pc, {'ReplaySourceRow', 'GeologyId', 'Level3CaseId', ...
    'Level3CaseName', 'Window', 'SliceIndex', 'GasSaturation', 'PcBar', ...
    'BulkSgMax', 'EffectiveSwi', 'AssignedState', 'SamplingPool', ...
    'SelectedSampleIndex', 'ReplaySeed'});
requireColumns(kr, {'PcReplaySourceRow', 'GeologyId', 'Level3CaseId', ...
    'Level3CaseName', 'Window', 'SliceIndex', 'ShapeId', ...
    'RepresentativeKrReplaySourceRow', 'EffectiveSwi', 'BulkSgMax', ...
    'NormalizedSg', 'GasSaturation', 'WaterSaturation', 'Krg', 'Krw'});
requireColumns(selection, {'GeologyId', 'Level3CaseId', ...
    'Level3CaseName', 'Window', 'SelectedReplaySourceRow', ...
    'SelectedEffectiveSwi'});
requireColumns(porosity, {'ReplaySourceRow', 'GeologyId', ...
    'Level3CaseId', 'Level3CaseName', 'Window', 'SliceIndex', ...
    'PoreVolume', 'BulkVolume', 'UpscaledPorosity'});

pc = normalizeKeyColumns(pc);
kr = normalizeKeyColumns(kr);
selection = normalizeKeyColumns(selection);
porosity = normalizeKeyColumns(porosity);
pc.ReplaySourceRow = numericColumn(pc.ReplaySourceRow);
kr.PcReplaySourceRow = numericColumn(kr.PcReplaySourceRow);
kr.RepresentativeKrReplaySourceRow = ...
    numericColumn(kr.RepresentativeKrReplaySourceRow);
selection.SelectedReplaySourceRow = ...
    numericColumn(selection.SelectedReplaySourceRow);
porosity.ReplaySourceRow = numericColumn(porosity.ReplaySourceRow);
porosity.PoreVolume = numericColumn(porosity.PoreVolume);
porosity.BulkVolume = numericColumn(porosity.BulkVolume);
porosity.UpscaledPorosity = numericColumn(porosity.UpscaledPorosity);

caseKeys = unique(pc(:, {'GeologyId', 'Level3CaseId'}), 'rows');
qaRows = cell(height(caseKeys), 40);
matFiles = strings(height(caseKeys), 1);

for c = 1:height(caseKeys)
    geologyId = caseKeys.GeologyId(c);
    caseId = caseKeys.Level3CaseId(c);
    pcCase = pc(pc.GeologyId == geologyId & pc.Level3CaseId == caseId, :);
    krCase = kr(kr.GeologyId == geologyId & kr.Level3CaseId == caseId, :);
    selectionCase = selection(selection.GeologyId == geologyId & ...
        selection.Level3CaseId == caseId, :);
    porosityCase = porosity(porosity.GeologyId == geologyId & ...
        porosity.Level3CaseId == caseId, :);
    assert(~isempty(krCase) && ~isempty(selectionCase) && ...
        ~isempty(porosityCase), ...
        'ReservoirReady:MissingCaseData', ...
        'Missing Kr, selection, or porosity data for %s case %02d.', ...
        geologyId, caseId);

    windows = orderedWindows(pcCase.Window);
    assert(numel(windows) == opt.ExpectedWindowCount, ...
        'ReservoirReady:WindowCount', ...
        'Expected %d windows for %s case %02d; found %d.', ...
        opt.ExpectedWindowCount, geologyId, caseId, numel(windows));
    assert(isequal(windows, orderedWindows(krCase.Window)), ...
        'ReservoirReady:WindowMismatch', ...
        'Pc and Kr window labels differ for %s case %02d.', geologyId, caseId);
    assert(isequal(windows, orderedWindows(porosityCase.Window)), ...
        'ReservoirReady:PorosityWindowMismatch', ...
        'Pc and porosity window labels differ for %s case %02d.', ...
        geologyId, caseId);

    referenceSlices = unique(pcCase.SliceIndex(pcCase.Window == windows(1)), ...
        'sorted');
    assert(numel(referenceSlices) == opt.ExpectedSliceCount, ...
        'ReservoirReady:SliceCount', ...
        'Expected %d slices for %s case %02d; found %d.', ...
        opt.ExpectedSliceCount, geologyId, caseId, numel(referenceSlices));

    nWindows = numel(windows);
    nSlices = numel(referenceSlices);
    [effectivePermeability, maxSourceLogMismatch] = ...
        extractEffectivePermeability( ...
        fieldPerm, geologyId, caseId, windows, referenceSlices, ...
        opt.PermeabilityTolerance);
    pcCurves = cell(nWindows, nSlices);
    krCurves = cell(nWindows, nSlices);
    upscaledPorosity = nan(nWindows, nSlices);
    maxEndpointMismatch = 0;
    maxPorosityIdentityMismatch = 0;
    maxSelectedSampleIndexMismatch = 0;
    maxReplaySeedMismatch = 0;
    maxPcMonotonicDrop = 0;
    maxKrgMonotonicDrop = 0;
    maxKrwMonotonicRise = 0;

    for w = 1:nWindows
        windowName = windows(w);
        pcSlices = unique(pcCase.SliceIndex(pcCase.Window == windowName), ...
            'sorted');
        krSlices = unique(krCase.SliceIndex(krCase.Window == windowName), ...
            'sorted');
        porositySlices = unique(porosityCase.SliceIndex( ...
            porosityCase.Window == windowName), 'sorted');
        assert(isequal(pcSlices, referenceSlices) && ...
            isequal(krSlices, referenceSlices) && ...
            isequal(porositySlices, referenceSlices), ...
            'ReservoirReady:SliceCoverage', ...
            'Incomplete Pc/Kr/porosity coverage for %s case %02d, %s.', ...
            geologyId, caseId, windowName);

        selected = selectionCase(selectionCase.Window == windowName, :);
        assert(height(selected) == 1, ...
            'ReservoirReady:SelectionCount', ...
            'Expected one Swi-medoid selection for %s case %02d, %s.', ...
            geologyId, caseId, windowName);
        representativeRows = unique(krCase.RepresentativeKrReplaySourceRow( ...
            krCase.Window == windowName));
        assert(isscalar(representativeRows) && ...
            representativeRows == selected.SelectedReplaySourceRow(1), ...
            'ReservoirReady:RepresentativeMismatch', ...
            'Kr representative does not match the Swi medoid for %s case %02d, %s.', ...
            geologyId, caseId, windowName);
        selectedPcRows = pcCase(pcCase.Window == windowName & ...
            pcCase.ReplaySourceRow == selected.SelectedReplaySourceRow(1), :);
        assert(~isempty(selectedPcRows), ...
            'ReservoirReady:SelectedPcMissing', ...
            'Selected Swi-medoid Pc realization is missing for %s case %02d, %s.', ...
            geologyId, caseId, windowName);
        selectedPcSwi = uniqueNumericScalar(selectedPcRows.EffectiveSwi, ...
            'selected Pc EffectiveSwi');
        selectedTableSwi = uniqueNumericScalar(selected.SelectedEffectiveSwi, ...
            'selected table EffectiveSwi');
        assert(abs(selectedPcSwi - selectedTableSwi) <= ...
            opt.EndpointTolerance, 'ReservoirReady:SelectedSwiMismatch', ...
            'Selected Swi does not match its Pc curve for %s case %02d, %s.', ...
            geologyId, caseId, windowName);

        for s = 1:nSlices
            sliceId = referenceSlices(s);
            P = pcCase(pcCase.Window == windowName & ...
                pcCase.SliceIndex == sliceId, :);
            K = krCase(krCase.Window == windowName & ...
                krCase.SliceIndex == sliceId, :);
            Phi = porosityCase(porosityCase.Window == windowName & ...
                porosityCase.SliceIndex == sliceId, :);
            assert(~isempty(P) && ~isempty(K) && height(Phi) == 1, ...
                'ReservoirReady:MissingCurve', ...
                ['Missing Pc/Kr data or nonunique porosity for %s case ', ...
                 '%02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);

            P = sortrows(P, 'GasSaturation');
            K = sortrows(K, 'NormalizedSg');
            pcSg = numericColumn(P.GasSaturation);
            pcBar = numericColumn(P.PcBar);
            krSg = numericColumn(K.GasSaturation);
            krSw = numericColumn(K.WaterSaturation);
            krg = numericColumn(K.Krg);
            krw = numericColumn(K.Krw);
            pcReplaySource = uniqueNumericScalar(P.ReplaySourceRow, ...
                'Pc replay source row');
            krPcReplaySource = uniqueNumericScalar(K.PcReplaySourceRow, ...
                'Kr Pc replay source row');
            assert(pcReplaySource == krPcReplaySource, ...
                'ReservoirReady:ReplaySourceMismatch', ...
                'Pc/Kr replay source differs for %s case %02d, %s, slice %d.', ...
                geologyId, caseId, windowName, sliceId);
            porosityReplaySource = uniqueNumericScalar( ...
                Phi.ReplaySourceRow, 'porosity replay source row');
            assert(pcReplaySource == porosityReplaySource, ...
                'ReservoirReady:PorosityReplaySourceMismatch', ...
                ['Pc and porosity replay sources differ for %s case ', ...
                 '%02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);

            selectedSampleIndex = uniqueNumericScalar( ...
                P.SelectedSampleIndex, 'Pc selected sample index');
            replaySeed = uniqueNumericScalar(P.ReplaySeed, 'Pc replay seed');
            assignedState = uniqueStringScalar( ...
                P.AssignedState, 'Pc assigned state');
            samplingPool = uniqueStringScalar( ...
                P.SamplingPool, 'Pc sampling pool');
            sampleIndexMismatch = abs(selectedSampleIndex - double( ...
                effectivePermeability.selectedSampleIndex(w, s)));
            replaySeedMismatch = abs(replaySeed - double( ...
                effectivePermeability.exactReplaySeed(w, s)));
            maxSelectedSampleIndexMismatch = max( ...
                maxSelectedSampleIndexMismatch, sampleIndexMismatch);
            maxReplaySeedMismatch = max( ...
                maxReplaySeedMismatch, replaySeedMismatch);
            assert(sampleIndexMismatch == 0, ...
                'ReservoirReady:PermeabilitySampleMismatch', ...
                ['Permeability and Pc selected-sample indices differ for ', ...
                 '%s case %02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);
            assert(replaySeedMismatch == 0, ...
                'ReservoirReady:PermeabilitySeedMismatch', ...
                ['Permeability and Pc replay seeds differ for %s case ', ...
                 '%02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);
            assert(assignedState == ...
                effectivePermeability.assignedState(w), ...
                'ReservoirReady:PermeabilityStateMismatch', ...
                ['Permeability and Pc assigned states differ for %s case ', ...
                 '%02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);
            assert(samplingPool == ...
                effectivePermeability.samplingPool(w), ...
                'ReservoirReady:PermeabilityPoolMismatch', ...
                ['Permeability and Pc sampling pools differ for %s case ', ...
                 '%02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);

            phiValue = uniqueNumericScalar(Phi.UpscaledPorosity, ...
                'upscaled porosity');
            poreVolume = uniqueNumericScalar(Phi.PoreVolume, 'pore volume');
            bulkVolume = uniqueNumericScalar(Phi.BulkVolume, 'bulk volume');
            assert(bulkVolume > 0 && phiValue >= 0 && phiValue <= 1, ...
                'ReservoirReady:PorosityBounds', ...
                ['Upscaled porosity or bulk volume is nonphysical for ', ...
                 '%s case %02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);
            porosityIdentityMismatch = abs(phiValue - ...
                poreVolume ./ bulkVolume);
            maxPorosityIdentityMismatch = max( ...
                maxPorosityIdentityMismatch, porosityIdentityMismatch);
            assert(porosityIdentityMismatch <= opt.PorosityTolerance, ...
                'ReservoirReady:PorosityIdentityMismatch', ...
                ['Upscaled porosity differs from pore-volume/bulk-volume ', ...
                 'by %.3g for %s case %02d, %s, slice %d.'], ...
                porosityIdentityMismatch, geologyId, caseId, ...
                windowName, sliceId);
            upscaledPorosity(w, s) = phiValue;
            bulkSgMaxPc = uniqueNumericScalar(P.BulkSgMax, ...
                'Pc BulkSgMax');
            effectiveSwiPc = uniqueNumericScalar(P.EffectiveSwi, ...
                'Pc EffectiveSwi');
            bulkSgMaxKr = uniqueNumericScalar(K.BulkSgMax, ...
                'Kr BulkSgMax');
            effectiveSwiKr = uniqueNumericScalar(K.EffectiveSwi, ...
                'Kr EffectiveSwi');

            endpointMismatch = max([ ...
                abs(bulkSgMaxPc - bulkSgMaxKr), ...
                abs(effectiveSwiPc - effectiveSwiKr), ...
                abs((1.0 - bulkSgMaxPc) - effectiveSwiPc), ...
                abs(max(pcSg) - bulkSgMaxPc), ...
                abs(max(krSg) - bulkSgMaxPc), ...
                max(abs(krSw - (1.0 - krSg)))]);
            maxEndpointMismatch = max(maxEndpointMismatch, endpointMismatch);
            assert(endpointMismatch <= opt.EndpointTolerance, ...
                'ReservoirReady:EndpointMismatch', ...
                ['Pc/Kr endpoint mismatch %.3g exceeds tolerance %.3g for ', ...
                 '%s case %02d, %s, slice %d.'], ...
                endpointMismatch, opt.EndpointTolerance, geologyId, ...
                caseId, windowName, sliceId);

            pcDrop = maximumDrop(pcBar);
            krgDrop = maximumDrop(krg);
            krwRise = maximumRise(krw);
            maxPcMonotonicDrop = max(maxPcMonotonicDrop, pcDrop);
            maxKrgMonotonicDrop = max(maxKrgMonotonicDrop, krgDrop);
            maxKrwMonotonicRise = max(maxKrwMonotonicRise, krwRise);
            assert(pcDrop <= opt.MonotonicTolerance, ...
                'ReservoirReady:NonmonotonicPc', ...
                'Pc is nonmonotonic for %s case %02d, %s, slice %d.', ...
                geologyId, caseId, windowName, sliceId);
            assert(krgDrop <= opt.MonotonicTolerance && ...
                krwRise <= opt.MonotonicTolerance, ...
                'ReservoirReady:NonmonotonicKr', ...
                'Kr is nonmonotonic for %s case %02d, %s, slice %d.', ...
                geologyId, caseId, windowName, sliceId);
            assert(all(krg >= -opt.MonotonicTolerance & ...
                krg <= 1 + opt.MonotonicTolerance) && ...
                all(krw >= -opt.MonotonicTolerance & ...
                krw <= 1 + opt.MonotonicTolerance), ...
                'ReservoirReady:KrBounds', ...
                'Kr lies outside [0,1] for %s case %02d, %s, slice %d.', ...
                geologyId, caseId, windowName, sliceId);

            pcCurves{w, s} = struct( ...
                'gasSaturation', pcSg, ...
                'pcBar', pcBar, ...
                'bulkSgMax', bulkSgMaxPc, ...
                'effectiveSwi', effectiveSwiPc, ...
                'replaySourceRow', pcReplaySource, ...
                'upscaledPorosity', phiValue);
            krCurves{w, s} = struct( ...
                'gasSaturation', krSg, ...
                'waterSaturation', krSw, ...
                'krg', krg, ...
                'krw', krw, ...
                'bulkSgMax', bulkSgMaxKr, ...
                'effectiveSwi', effectiveSwiKr, ...
                'shapeId', string(K.ShapeId(1)), ...
                'representativeReplaySourceRow', representativeRows);
        end
    end

    reservoirReady = struct();
    samplingCase = effectivePermeability.samplingCase;
    reservoirReady.schemaVersion = "1.7";
    reservoirReady.geologyId = geologyId;
    reservoirReady.level3CaseId = caseId;
    reservoirReady.level3CaseName = string(pcCase.Level3CaseName(1));
    reservoirReady.samplingCaseId = samplingCase.samplingCaseId;
    reservoirReady.phase = samplingCase.phase;
    reservoirReady.caseType = samplingCase.caseType;
    reservoirReady.replicateId = samplingCase.replicateId;
    reservoirReady.useForProbabilisticUq = ...
        samplingCase.useForProbabilisticUq;
    reservoirReady.isBenchmark = samplingCase.isBenchmark;
    reservoirReady.isStressTest = samplingCase.isStressTest;
    reservoirReady.samplingCase = samplingCase;
    reservoirReady.windowLabels = windows;
    reservoirReady.sliceIndices = referenceSlices;
    reservoirReady.windowSliceMap = buildWindowSliceMap( ...
        windows, referenceSlices);
    reservoirReady.predictRealizationIdMap = ...
        effectivePermeability.predictRealizationId;
    reservoirReady.Kxx_mD = effectivePermeability.mD(:, :, 1);
    reservoirReady.Kyy_mD = effectivePermeability.mD(:, :, 2);
    reservoirReady.Kzz_mD = effectivePermeability.mD(:, :, 3);
    reservoirReady.Kxx_SI = effectivePermeability.squareMeters(:, :, 1);
    reservoirReady.Kyy_SI = effectivePermeability.squareMeters(:, :, 2);
    reservoirReady.Kzz_SI = effectivePermeability.squareMeters(:, :, 3);
    reservoirReady.pcCurves = pcCurves;
    reservoirReady.krCurves = krCurves;
    reservoirReady.pcRepresentation = "full_slice";
    reservoirReady.effectivePermeability = effectivePermeability;
    reservoirReady.effectivePorosity = upscaledPorosity;
    reservoirReady.upscaledPorosity = upscaledPorosity;
    reservoirReady.SwiEff = extractEffectiveSwiMap(pcCurves);
    reservoirReady.swiMedoidSelection = selectionCase;
    reservoirReady.samplingManifestHash = ...
        samplingCase.samplingManifestSha256;
    reservoirReady.replayManifestHash = replayManifestSha256;
    reservoirReady.configurationHash = productionMethodConfigHash;
    reservoirReady.provenance = struct( ...
        'pcNativeSource', pcSource, ...
        'krSliceSource', krSource, ...
        'selectionSource', selectionSource, ...
        'porositySource', porositySource, ...
        'permeabilitySource', permeabilitySource, ...
        'replayManifestSource', replayManifestSource, ...
        'replayManifestSha256', replayManifestSha256, ...
        'productionMethodConfigSha256', productionMethodConfigHash, ...
        'samplingManifestSha256', samplingCase.samplingManifestSha256, ...
        'samplingMethodConfigHash', ...
            samplingCase.samplingMethodConfigHash, ...
        'samplingCodeCommit', samplingCase.samplingCodeCommit, ...
        'predictMethodConfigHash', samplingCase.predictMethodConfigHash, ...
        'predictCodeCommit', samplingCase.predictCodeCommit, ...
        'createdAt', string(datetime('now', 'TimeZone', 'UTC')));
    validateRevisedOutputProvenance(reservoirReady);
    reservoirReady.saturationRegions = ...
        build_saturation_region_metadata(reservoirReady);

    matFile = fullfile(outputDir, fault_properties_filename( ...
        geologyId, caseId, "full_slice"));
    save(matFile, 'reservoirReady', '-v7.3');
    matFiles(c) = string(matFile);
    qaRows(c, :) = {geologyId, caseId, ...
        string(pcCase.Level3CaseName(1)), nWindows, nSlices, ...
        nWindows * nSlices, nWindows * nSlices, numel(upscaledPorosity), ...
        nWindows * nSlices, numel(effectivePermeability.componentLabels), ...
        height(selectionCase), min(upscaledPorosity, [], 'all'), ...
        max(upscaledPorosity, [], 'all'), ...
        min(effectivePermeability.mD, [], 'all'), ...
        max(effectivePermeability.mD, [], 'all'), ...
        maxSourceLogMismatch, ...
        maxSelectedSampleIndexMismatch, maxReplaySeedMismatch, ...
        maxPorosityIdentityMismatch, maxEndpointMismatch, ...
        maxPcMonotonicDrop, maxKrgMonotonicDrop, ...
        maxKrwMonotonicRise, true, string(matFile), ...
        reservoirReady.schemaVersion, ...
        reservoirReady.samplingCaseId, reservoirReady.phase, ...
        reservoirReady.caseType, reservoirReady.replicateId, ...
        reservoirReady.useForProbabilisticUq, ...
        reservoirReady.isBenchmark, reservoirReady.isStressTest, ...
        reservoirReady.effectivePermeability.assignmentMetadataExplicit, ...
        reservoirReady.samplingManifestHash, ...
        reservoirReady.replayManifestHash, ...
        reservoirReady.configurationHash, ...
        reservoirReady.provenance.samplingCodeCommit, ...
        reservoirReady.provenance.predictCodeCommit, ...
        string(reservoirReady.effectivePermeability.coordinateContract.downstream_transform_contract)};
end

qa = cell2table(qaRows, 'VariableNames', { ...
    'GeologyId', 'Level3CaseId', 'Level3CaseName', 'WindowCount', ...
    'SliceCount', 'PcCurveCount', 'KrCurveCount', ...
    'PorosityCount', 'PermeabilityCellCount', ...
    'PermeabilityComponentCount', 'SwiMedoidSelectionCount', ...
    'MinUpscaledPorosity', 'MaxUpscaledPorosity', ...
    'MinPermeabilityMD', 'MaxPermeabilityMD', ...
    'MaxSourceLogPermeabilityMismatch', ...
    'MaxSelectedSampleIndexMismatch', 'MaxReplaySeedMismatch', ...
    'MaxPorosityIdentityMismatch', 'MaxEndpointMismatch', ...
    'MaxPcMonotonicDrop', 'MaxKrgMonotonicDrop', ...
    'MaxKrwMonotonicRise', 'Passed', 'MatFile', ...
    'SchemaVersion', 'SamplingCaseId', 'Phase', 'CaseType', ...
    'ReplicateId', 'UseForProbabilisticUq', 'IsBenchmark', ...
    'IsStressTest', 'AssignmentMetadataExplicit', ...
    'SamplingManifestHash', 'ReplayManifestHash', ...
    'ConfigurationHash', 'SamplingCodeCommit', 'PredictCodeCommit', ...
    'CoordinateTransformContract'});
qaFile = fullfile(outputDir, 'reservoir_ready_qa_summary.csv');
writetable(qa, qaFile);

outputs = struct('matFiles', matFiles, 'qaTable', qa, ...
    'qaCsv', string(qaFile));
fprintf('Saved %d downstream fault-property MAT file(s): %s\n', ...
    numel(matFiles), outputDir);
fprintf('Saved reservoir-ready QA summary: %s\n', qaFile);
end


function [fieldPerm, source] = loadPermeabilityInput(value)
% Load the canonical field permeability struct from memory or MAT storage.

if isstruct(value)
    if isfield(value, 'fieldPerm')
        fieldPerm = value.fieldPerm;
    else
        fieldPerm = value;
    end
    source = "in-memory fieldPerm struct";
else
    file = string(value);
    assert(isscalar(file) && isfile(file), ...
        'ReservoirReady:MissingPermeabilityInput', ...
        'Permeability MAT input not found: %s', file);
    loaded = load(file, 'fieldPerm');
    assert(isfield(loaded, 'fieldPerm'), ...
        'ReservoirReady:MissingFieldPerm', ...
        'Permeability MAT file does not contain fieldPerm: %s', file);
    fieldPerm = loaded.fieldPerm;
    source = file;
end

required = {'geology_id', 'level3_case_id', 'slice_index', 'window', ...
    'component', 'perm', 'logK', 'selected_sample_index', ...
    'exact_replay_seed', 'assigned_state', 'sampling_pool'};
missing = required(~isfield(fieldPerm, required));
assert(isempty(missing), 'ReservoirReady:MissingFieldPermFields', ...
    'fieldPerm is missing fields: %s', strjoin(missing, ', '));
end


function [permeability, sourceLogMismatch] = extractEffectivePermeability( ...
        fieldPerm, geologyId, caseId, windows, slices, tolerance)
% Extract and validate one case as window-by-slice-by-component arrays.

geologyLabels = string(fieldPerm.geology_id(:));
caseLabels = double(fieldPerm.level3_case_id(:));
sliceLabels = double(fieldPerm.slice_index(:));
windowLabels = string(fieldPerm.window(:));
componentLabels = string(fieldPerm.component(:));

g = find(geologyLabels == string(geologyId));
c = find(caseLabels == double(caseId));
[sliceFound, s] = ismember(double(slices(:)), sliceLabels);
[windowFound, w] = ismember(string(windows(:)), windowLabels);
requestedComponents = ["kxx"; "kyy"; "kzz"];
[componentFound, componentIndex] = ismember( ...
    requestedComponents, componentLabels);
assert(isscalar(g) && isscalar(c), ...
    'ReservoirReady:PermeabilityCaseLookup', ...
    'Permeability input lacks one unique match for %s case %02d.', ...
    geologyId, caseId);
assert(all(sliceFound) && all(windowFound) && all(componentFound), ...
    'ReservoirReady:PermeabilityAxisLookup', ...
    ['Permeability input lacks one or more requested slices, windows, ', ...
     'or components for %s case %02d.'], geologyId, caseId);

expectedSize = [numel(geologyLabels), numel(caseLabels), ...
    numel(sliceLabels), numel(windowLabels), numel(componentLabels)];
assert(isequal(size(fieldPerm.perm), expectedSize) && ...
    isequal(size(fieldPerm.logK), expectedSize), ...
    'ReservoirReady:PermeabilityArraySize', ...
    'fieldPerm permeability arrays do not match their labeled dimensions.');

nSlices = numel(s);
nWindows = numel(w);
rawMD = fieldPerm.perm(g, c, s, w, componentIndex);
rawLog = fieldPerm.logK(g, c, s, w, componentIndex);
mD = permute(reshape(double(rawMD), ...
    [nSlices, nWindows, numel(componentIndex)]), [2, 1, 3]);
sourceLog10mD = permute(reshape(double(rawLog), ...
    [nSlices, nWindows, numel(componentIndex)]), [2, 1, 3]);
assert(all(isfinite(mD), 'all') && all(mD > 0, 'all') && ...
    all(isfinite(sourceLog10mD), 'all'), ...
    'ReservoirReady:InvalidPermeability', ...
    'Permeability values must be positive and finite.');

sourceLogMismatch = max(abs(sourceLog10mD - log10(mD)), [], 'all');
assert(sourceLogMismatch <= tolerance, ...
    'ReservoirReady:PermeabilityLogMismatch', ...
    ['Stored log10 permeability differs from log10(mD) by %.3g for ', ...
     '%s case %02d.'], sourceLogMismatch, geologyId, caseId);

sampleRaw = fieldPerm.selected_sample_index(g, c, s, w);
seedRaw = fieldPerm.exact_replay_seed(g, c, s, w);
selectedSampleIndex = permute(reshape(sampleRaw, ...
    [nSlices, nWindows]), [2, 1]);
exactReplaySeed = permute(reshape(seedRaw, ...
    [nSlices, nWindows]), [2, 1]);
assert(all(selectedSampleIndex > 0, 'all') && ...
    all(exactReplaySeed > 0, 'all'), ...
    'ReservoirReady:InvalidReplayMetadata', ...
    'Selected sample indices and replay seeds must be positive.');

assignedState = reshape(string(fieldPerm.assigned_state(g, c, w)), ...
    [nWindows, 1]);
samplingPool = reshape(string(fieldPerm.sampling_pool(g, c, w)), ...
    [nWindows, 1]);

hasRevisedAssignmentMetadata = all(isfield(fieldPerm, { ...
    'predict_realization_id', 'sampling_seed', 'checkpoint_sha256', ...
    'checkpoint_relative_path'}));
if hasRevisedAssignmentMetadata
    realizationRaw = fieldPerm.predict_realization_id(g, c, s, w);
    predictRealizationId = permute(reshape(realizationRaw, ...
        [nSlices, nWindows]), [2, 1]);
    samplingSeed = reshape(fieldPerm.sampling_seed(g, c, w), ...
        [nWindows, 1]);
    checkpointSha256 = reshape(string(fieldPerm.checkpoint_sha256(g, w)), ...
        [nWindows, 1]);
    checkpointRelativePath = reshape(string( ...
        fieldPerm.checkpoint_relative_path(g, w)), [nWindows, 1]);
    if isfield(fieldPerm, 'source_checkpoint_file')
        sourceCheckpointFile = reshape(string( ...
            fieldPerm.source_checkpoint_file(g, w)), [nWindows, 1]);
    else
        sourceCheckpointFile = strings(nWindows, 1);
    end
    assert(all(predictRealizationId > 0, 'all') && ...
        all(samplingSeed >= 0, 'all'), ...
        'ReservoirReady:InvalidSamplingMetadata', ...
        'PREDICT realization IDs and sampling seeds are invalid.');
    assert(all(cellfun(@isSha256, cellstr(checkpointSha256))), ...
        'ReservoirReady:CheckpointHash', ...
        'Every revised-design window must have a valid checkpoint SHA-256.');
    assert(all(strlength(checkpointRelativePath) > 0), ...
        'ReservoirReady:CheckpointPath', ...
        'Every revised-design window must have a checkpoint-relative path.');
else
    predictRealizationId = selectedSampleIndex;
    samplingSeed = zeros(nWindows, 1, 'int64');
    checkpointSha256 = strings(nWindows, 1);
    checkpointRelativePath = strings(nWindows, 1);
    sourceCheckpointFile = strings(nWindows, 1);
end

permeability = struct();
permeability.dimensionOrder = "window x slice x component";
permeability.componentLabels = requestedComponents;
permeability.units = struct('mD', "millidarcy", ...
    'squareMeters', "m^2");
permeability.mD = mD;
permeability.squareMeters = mD .* 9.869233e-16;
permeability.selectedSampleIndex = selectedSampleIndex;
permeability.predictRealizationId = predictRealizationId;
permeability.exactReplaySeed = exactReplaySeed;
permeability.samplingSeed = samplingSeed;
permeability.checkpointSha256 = checkpointSha256;
permeability.checkpointRelativePath = checkpointRelativePath;
permeability.sourceCheckpointFile = sourceCheckpointFile;
permeability.assignmentMetadataExplicit = hasRevisedAssignmentMetadata;
permeability.assignedState = assignedState;
permeability.samplingPool = samplingPool;
permeability.coordinateFrame = "fault_local";
permeability.componentMeanings = ["fault_normal"; ...
    "along_strike"; "down_dip"];
permeability.rotationApplied = false;
permeability.transformRequired = true;
permeability.coordinateContract = extractCoordinateContract(fieldPerm);
permeability.samplingCase = extractSamplingCase(fieldPerm, g, c);
end


function contract = extractCoordinateContract(fieldPerm)
% Preserve the explicit fault-local tensor contract for downstream rotation.

if isfield(fieldPerm, 'coordinate_contract')
    source = fieldPerm.coordinate_contract;
    required = {'schema_version', 'stored_coordinate_system', ...
        'component_labels', 'component_meanings', ...
        'reservoir_coordinate_system', 'rotation_required', ...
        'downstream_transform_contract', 'pre_rotated', ...
        'tensor_formula', 'component_formula', 'geometry_dependency'};
    missing = required(~isfield(source, required));
    assert(isempty(missing), 'ReservoirReady:CoordinateContractFields', ...
        'fieldPerm coordinate contract is missing fields: %s', ...
        strjoin(missing, ', '));
    contract = source;
else
    % Legacy fieldPerm files store the same PREDICT-local components but did
    % not describe the frame explicitly. Keep support while making the
    % downstream transformation requirement unambiguous.
    contract = defaultFaultLocalCoordinateContract();
    contract.sourceMetadataStatus = "inferred_from_legacy_fieldPerm";
end

assert(logical(contract.rotation_required), ...
    'ReservoirReady:CoordinateRotationRequired', ...
    'Fault-local permeability must require downstream coordinate rotation.');
assert(~logical(contract.pre_rotated), ...
    'ReservoirReady:CoordinatePreRotation', ...
    'fieldPerm must contain unrotated PREDICT fault-local components.');
assert(string(contract.downstream_transform_contract) == ...
    "fault_local_to_reservoir_grid_signed_yz_v1", ...
    'ReservoirReady:CoordinateTransformVersion', ...
    'Unexpected downstream permeability-transform contract.');
end


function contract = defaultFaultLocalCoordinateContract()
contract = struct( ...
    'schema_version', "fault_local_coordinate_contract_v1", ...
    'stored_coordinate_system', ...
        "PREDICT fault-local orthonormal axes", ...
    'component_labels', ["kxx"; "kyy"; "kzz"], ...
    'component_meanings', ...
        ["fault_normal"; "along_strike"; "down_dip"], ...
    'reservoir_coordinate_system', "reservoir-grid Cartesian axes", ...
    'rotation_required', true, ...
    'downstream_transform_contract', ...
        "fault_local_to_reservoir_grid_signed_yz_v1", ...
    'global_x_mapping', ...
        "reservoir Kxx equals fault-local kyy (along strike)", ...
    'yz_rotation', ...
        "theta = sign(dY/dZ) * (dip_deg - 90 deg)", ...
    'tensor_formula', ...
        "K_global = R * diag(kxx_local, kyy_local, kzz_local) * transpose(R)", ...
    'component_formula', ...
        ["Kxx=kyy; Kyy=cos(theta)^2*kxx+sin(theta)^2*kzz; ", ...
         "Kyz=cos(theta)*sin(theta)*(kxx-kzz); ", ...
         "Kzz=sin(theta)^2*kxx+cos(theta)^2*kzz; Kxy=Kxz=0"], ...
    'pre_rotated', false, ...
    'geometry_dependency', ...
        ["theta must be calculated from the paired fault-node trace ", ...
         "for each reservoir fault cell"]);
end


function samplingCase = extractSamplingCase(fieldPerm, geologyIndex, caseIndex)
% Read explicit revised-design role metadata without inferring probabilities.

required = {'sampling_case_id', 'phase', 'case_type', 'replicate_id', ...
    'use_for_probabilistic_uq', 'is_benchmark', 'is_stress_test'};
hasExplicitRole = all(isfield(fieldPerm, required));
if hasExplicitRole
    samplingCase = struct( ...
        'metadataExplicit', true, ...
        'samplingCaseId', string(fieldPerm.sampling_case_id( ...
            geologyIndex, caseIndex)), ...
        'phase', string(fieldPerm.phase(geologyIndex, caseIndex)), ...
        'caseType', string(fieldPerm.case_type(geologyIndex, caseIndex)), ...
        'replicateId', double(fieldPerm.replicate_id( ...
            geologyIndex, caseIndex)), ...
        'useForProbabilisticUq', logical( ...
            fieldPerm.use_for_probabilistic_uq(geologyIndex, caseIndex)), ...
        'isBenchmark', logical(fieldPerm.is_benchmark( ...
            geologyIndex, caseIndex)), ...
        'isStressTest', logical(fieldPerm.is_stress_test( ...
            geologyIndex, caseIndex)));
    validateSamplingCaseRole(samplingCase)
else
    samplingCase = struct( ...
        'metadataExplicit', false, ...
        'samplingCaseId', "", ...
        'phase', "legacy", ...
        'caseType', "legacy_level3_case", ...
        'replicateId', NaN, ...
        'useForProbabilisticUq', false, ...
        'isBenchmark', false, ...
        'isStressTest', false);
end

samplingCase.samplingManifestSha256 = optionalScalarString( ...
    fieldPerm, 'sampling_manifest_sha256');
samplingCase.samplingMethodConfigHash = optionalScalarString( ...
    fieldPerm, 'sampling_method_config_hash');
samplingCase.samplingCodeCommit = optionalScalarString( ...
    fieldPerm, 'sampling_code_commit');
samplingCase.predictMethodConfigHash = optionalScalarString( ...
    fieldPerm, 'predict_method_config_hash');
samplingCase.predictCodeCommit = optionalScalarString( ...
    fieldPerm, 'predict_code_commit');
end


function validateSamplingCaseRole(caseMetadata)
caseType = string(caseMetadata.caseType);
switch caseType
    case "independent_full"
        expected = [true, false, false];
        assert(caseMetadata.replicateId >= 1 && ...
            caseMetadata.replicateId <= 52, ...
            'ReservoirReady:SamplingReplicate', ...
            'Independent replicate ID must lie in 1:52.');
    case "representative_medoid"
        expected = [false, true, false];
        assert(caseMetadata.replicateId == 0, ...
            'ReservoirReady:SamplingReplicate', ...
            'Representative benchmark must use replicate ID 0.');
    case {"low_state_stress", "high_state_stress"}
        expected = [false, false, true];
        assert(caseMetadata.replicateId == 0, ...
            'ReservoirReady:SamplingReplicate', ...
            'Stress benchmarks must use replicate ID 0.');
    otherwise
        error('ReservoirReady:SamplingCaseType', ...
            'Unsupported revised sampling case type: %s', caseType);
end
actual = [caseMetadata.useForProbabilisticUq, ...
    caseMetadata.isBenchmark, caseMetadata.isStressTest];
assert(isequal(actual, expected), 'ReservoirReady:SamplingCaseRole', ...
    'Sampling role flags do not match case type %s.', caseType);
assert(strlength(caseMetadata.samplingCaseId) > 0, ...
    'ReservoirReady:SamplingCaseId', ...
    'Explicit revised sampling metadata requires a sampling case ID.');
end


function value = optionalScalarString(source, fieldName)
if isfield(source, fieldName)
    value = string(source.(fieldName));
    assert(isscalar(value), 'ReservoirReady:ScalarProvenance', ...
        'Expected scalar provenance field %s.', fieldName);
else
    value = "";
end
end


function map = buildWindowSliceMap(windows, slices)
% Build explicit 6-by-87 labels for downstream fault-cell mapping.

nWindows = numel(windows);
nSlices = numel(slices);
map = struct( ...
    'dimensionOrder', "window x slice", ...
    'windowId', repmat(reshape(string(windows), [nWindows, 1]), ...
        1, nSlices), ...
    'sliceId', repmat(reshape(double(slices), [1, nSlices]), ...
        nWindows, 1));
end


function swi = extractEffectiveSwiMap(pcCurves)
% Extract one physical Pc endpoint for every window-slice cell.

swi = nan(size(pcCurves));
for index = 1:numel(pcCurves)
    swi(index) = pcCurves{index}.effectiveSwi;
end
end


function validateRevisedOutputProvenance(reservoirReady)
% Require complete immutable provenance for the revised production design.

if ~reservoirReady.samplingCase.metadataExplicit
    return
end
assert(reservoirReady.effectivePermeability.assignmentMetadataExplicit, ...
    'ReservoirReady:AssignmentProvenance', ...
    'Revised sampling cases require explicit assignment provenance.');
requiredHashes = [ ...
    string(reservoirReady.samplingManifestHash), ...
    string(reservoirReady.replayManifestHash), ...
    string(reservoirReady.configurationHash), ...
    string(reservoirReady.provenance.samplingMethodConfigHash), ...
    string(reservoirReady.provenance.predictMethodConfigHash)];
assert(all(cellfun(@isSha256, cellstr(requiredHashes))), ...
    'ReservoirReady:IncompleteHashProvenance', ...
    ['Revised sampling outputs require SHA-256 hashes for the sampling ', ...
     'manifest, replay manifest, production configuration, sampling ', ...
     'configuration, and PREDICT configuration.']);
assert(strlength(string(reservoirReady.provenance.samplingCodeCommit)) > 0 && ...
    strlength(string(reservoirReady.provenance.predictCodeCommit)) > 0, ...
    'ReservoirReady:IncompleteCommitProvenance', ...
    'Revised sampling outputs require sampling and PREDICT code commits.');
end


function tf = isSha256(value)
% Return true only for one lowercase or uppercase hexadecimal SHA-256 value.

value = char(string(value));
tf = ~isempty(regexp(value, '^[0-9a-fA-F]{64}$', 'once'));
end


function value = sha256File(file)
% Compute SHA-256 incrementally without loading a complete file into memory.

file = char(string(file));
fid = fopen(file, 'rb');
assert(fid >= 0, 'ReservoirReady:ReplayManifestHashRead', ...
    'Could not open file for hashing: %s', file);
cleanup = onCleanup(@() fclose(fid));
digest = java.security.MessageDigest.getInstance('SHA-256');
while true
    bytes = fread(fid, 1024 * 1024, '*uint8');
    if isempty(bytes)
        break
    end
    digest.update(bytes);
end
bytes = typecast(digest.digest(), 'uint8');
value = lower(string(reshape(dec2hex(bytes, 2).', 1, [])));
clear cleanup
end


function [T, source] = loadInputTable(value, label)
% Read a table input or return an existing table unchanged.

if istable(value)
    T = value;
    source = "in-memory " + string(label) + " table";
else
    file = string(value);
    assert(isscalar(file) && isfile(file), ...
        'ReservoirReady:MissingInput', '%s input not found: %s', label, file);
    T = readtable(file, 'TextType', 'string');
    source = file;
end
end


function T = normalizeKeyColumns(T)
% Normalize shared case keys to stable string/numeric types.

T.GeologyId = string(T.GeologyId);
T.Level3CaseId = numericColumn(T.Level3CaseId);
T.Level3CaseName = string(T.Level3CaseName);
T.Window = string(T.Window);
if ismember('SliceIndex', T.Properties.VariableNames)
    T.SliceIndex = numericColumn(T.SliceIndex);
end
end


function requireColumns(T, required)
% Require all named columns in a table.

missing = setdiff(required, T.Properties.VariableNames);
assert(isempty(missing), 'ReservoirReady:MissingColumns', ...
    'Input table is missing columns: %s', strjoin(missing, ', '));
end


function values = numericColumn(values)
% Convert a table variable to a double column.

if ~isnumeric(values)
    values = str2double(string(values));
end
values = double(values(:));
assert(all(isfinite(values)), 'ReservoirReady:NonfiniteColumn', ...
    'Expected a finite numeric column.');
end


function value = uniqueNumericScalar(values, label)
% Return one repeated numeric metadata value.

values = numericColumn(values);
value = values(1);
tolerance = 1.0e-12 * max(1, abs(value));
assert(all(abs(values - value) <= tolerance), ...
    'ReservoirReady:InconsistentMetadata', ...
    '%s is inconsistent within one curve.', label);
end


function value = uniqueStringScalar(values, label)
% Return one repeated string metadata value.

values = string(values(:));
value = values(1);
assert(all(values == value), 'ReservoirReady:InconsistentMetadata', ...
    '%s is inconsistent within one curve.', label);
end


function windows = orderedWindows(values)
% Return unique window labels ordered by their numeric suffix.

windows = unique(string(values), 'stable');
numbers = arrayfun(@windowNumber, windows);
[~, order] = sort(numbers);
windows = windows(order);
end


function value = windowNumber(label)
% Return the numeric suffix from a label such as famp6.

token = regexp(char(label), '(\d+)$', 'tokens', 'once');
assert(~isempty(token), 'ReservoirReady:WindowLabel', ...
    'Window label lacks a numeric suffix: %s', label);
value = str2double(token{1});
end


function value = maximumDrop(values)
% Return the largest decrease between adjacent values.

if numel(values) < 2
    value = 0;
else
    value = max([0; -diff(values(:))]);
end
end


function value = maximumRise(values)
% Return the largest increase between adjacent values.

if numel(values) < 2
    value = 0;
else
    value = max([0; diff(values(:))]);
end
end


function ensureFolder(folderPath)
% Create a folder when it does not exist.

if ~isfolder(folderPath)
    mkdir(folderPath);
end
end
