function outputs = export_reservoir_ready_pc_kr_cases( ...
        pcNativeInput, krSliceInput, selectionInput, outputDir, varargin)
%EXPORT_RESERVOIR_READY_PC_KR_CASES Validate and package fault-cell inputs.
%
%   OUTPUTS = EXPORT_RESERVOIR_READY_PC_KR_CASES(PCNATIVEINPUT,
%   KRSLICEINPUT, SELECTIONINPUT, OUTPUTDIR) accepts either tables or CSV
%   paths. POROSITYINPUT is supplied as a name-value option and contains
%   the volume-weighted porosity summary from Pc replay. For every
%   geology/case combination the function:
%     1. verifies complete window and slice coverage;
%     2. verifies one physical upscaled porosity per fault cell;
%     3. verifies that Pc and Kr use identical slice-specific Swi endpoints;
%     4. checks Pc/Kr monotonicity and physical Kr bounds;
%     5. verifies one Swi-medoid representative per window; and
%     6. writes one compact reservoir-ready MAT file plus a QA CSV.
%
%   Pc curves remain slice specific. Kr curves use one normalized dynamic
%   shape per window, mapped to each slice's own Pc-derived BulkSgMax. The
%   optional full-Pc-curve medoids are not consumed here.
%
%   Name-value options:
%     PorosityInput       required table or CSV path
%     ExpectedWindowCount  default 6
%     ExpectedSliceCount   default 87
%     EndpointTolerance    default 1e-10
%     MonotonicTolerance   default 1e-8
%     PorosityTolerance    default 1e-12

%   The MAT schema is intentionally independent of MRST so a reservoir
%   model can load and map the checked curves without rerunning upscaling.

p = inputParser;
addParameter(p, 'PorosityInput', [], ...
    @(x) isempty(x) || istable(x) || ischar(x) || isstring(x));
addParameter(p, 'ExpectedWindowCount', 6, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'ExpectedSliceCount', 87, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'EndpointTolerance', 1.0e-10, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'MonotonicTolerance', 1.0e-8, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'PorosityTolerance', 1.0e-12, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
parse(p, varargin{:});
opt = p.Results;
assert(~isempty(opt.PorosityInput), 'ReservoirReady:MissingPorosityInput', ...
    ['PorosityInput is required so every reservoir fault cell receives ', ...
     'an upscaled porosity.']);

[pc, pcSource] = loadInputTable(pcNativeInput, 'native Pc');
[kr, krSource] = loadInputTable(krSliceInput, 'slice Kr');
[selection, selectionSource] = loadInputTable(selectionInput, ...
    'Swi-medoid selection');
[porosity, porositySource] = loadInputTable(opt.PorosityInput, ...
    'upscaled porosity');
ensureFolder(outputDir);

requireColumns(pc, {'ReplaySourceRow', 'GeologyId', 'Level3CaseId', ...
    'Level3CaseName', 'Window', 'SliceIndex', 'GasSaturation', 'PcBar', ...
    'BulkSgMax', 'EffectiveSwi'});
requireColumns(kr, {'PcReplaySourceRow', 'GeologyId', 'Level3CaseId', ...
    'Level3CaseName', 'Window', 'SliceIndex', 'ShapeId', ...
    'RepresentativeKrReplaySourceRow', 'EffectiveSwi', 'BulkSgMax', ...
    'NormalizedSg', 'GasSaturation', 'WaterSaturation', 'Krg', 'Krw'});
requireColumns(selection, {'GeologyId', 'Level3CaseId', ...
    'Level3CaseName', 'Window', 'SelectedReplaySourceRow', ...
    'SelectedEffectiveSwi'});
requireColumns(porosity, {'ReplaySourceRow', 'GeologyId', ...
    'Level3CaseId', 'Level3CaseName', 'Window', 'SliceIndex', ...
    'PoreVolume', 'BulkVolume', 'UpscaledPorosity'});

pc = normalizeKeyColumns(pc);
kr = normalizeKeyColumns(kr);
selection = normalizeKeyColumns(selection);
porosity = normalizeKeyColumns(porosity);
pc.ReplaySourceRow = numericColumn(pc.ReplaySourceRow);
kr.PcReplaySourceRow = numericColumn(kr.PcReplaySourceRow);
kr.RepresentativeKrReplaySourceRow = ...
    numericColumn(kr.RepresentativeKrReplaySourceRow);
selection.SelectedReplaySourceRow = ...
    numericColumn(selection.SelectedReplaySourceRow);
porosity.ReplaySourceRow = numericColumn(porosity.ReplaySourceRow);
porosity.PoreVolume = numericColumn(porosity.PoreVolume);
porosity.BulkVolume = numericColumn(porosity.BulkVolume);
porosity.UpscaledPorosity = numericColumn(porosity.UpscaledPorosity);

caseKeys = unique(pc(:, {'GeologyId', 'Level3CaseId'}), 'rows');
qaRows = cell(height(caseKeys), 18);
matFiles = strings(height(caseKeys), 1);

for c = 1:height(caseKeys)
    geologyId = caseKeys.GeologyId(c);
    caseId = caseKeys.Level3CaseId(c);
    pcCase = pc(pc.GeologyId == geologyId & pc.Level3CaseId == caseId, :);
    krCase = kr(kr.GeologyId == geologyId & kr.Level3CaseId == caseId, :);
    selectionCase = selection(selection.GeologyId == geologyId & ...
        selection.Level3CaseId == caseId, :);
    porosityCase = porosity(porosity.GeologyId == geologyId & ...
        porosity.Level3CaseId == caseId, :);
    assert(~isempty(krCase) && ~isempty(selectionCase) && ...
        ~isempty(porosityCase), ...
        'ReservoirReady:MissingCaseData', ...
        'Missing Kr, selection, or porosity data for %s case %02d.', ...
        geologyId, caseId);

    windows = orderedWindows(pcCase.Window);
    assert(numel(windows) == opt.ExpectedWindowCount, ...
        'ReservoirReady:WindowCount', ...
        'Expected %d windows for %s case %02d; found %d.', ...
        opt.ExpectedWindowCount, geologyId, caseId, numel(windows));
    assert(isequal(windows, orderedWindows(krCase.Window)), ...
        'ReservoirReady:WindowMismatch', ...
        'Pc and Kr window labels differ for %s case %02d.', geologyId, caseId);
    assert(isequal(windows, orderedWindows(porosityCase.Window)), ...
        'ReservoirReady:PorosityWindowMismatch', ...
        'Pc and porosity window labels differ for %s case %02d.', ...
        geologyId, caseId);

    referenceSlices = unique(pcCase.SliceIndex(pcCase.Window == windows(1)), ...
        'sorted');
    assert(numel(referenceSlices) == opt.ExpectedSliceCount, ...
        'ReservoirReady:SliceCount', ...
        'Expected %d slices for %s case %02d; found %d.', ...
        opt.ExpectedSliceCount, geologyId, caseId, numel(referenceSlices));

    nWindows = numel(windows);
    nSlices = numel(referenceSlices);
    pcCurves = cell(nWindows, nSlices);
    krCurves = cell(nWindows, nSlices);
    upscaledPorosity = nan(nWindows, nSlices);
    maxEndpointMismatch = 0;
    maxPorosityIdentityMismatch = 0;
    maxPcMonotonicDrop = 0;
    maxKrgMonotonicDrop = 0;
    maxKrwMonotonicRise = 0;

    for w = 1:nWindows
        windowName = windows(w);
        pcSlices = unique(pcCase.SliceIndex(pcCase.Window == windowName), ...
            'sorted');
        krSlices = unique(krCase.SliceIndex(krCase.Window == windowName), ...
            'sorted');
        porositySlices = unique(porosityCase.SliceIndex( ...
            porosityCase.Window == windowName), 'sorted');
        assert(isequal(pcSlices, referenceSlices) && ...
            isequal(krSlices, referenceSlices) && ...
            isequal(porositySlices, referenceSlices), ...
            'ReservoirReady:SliceCoverage', ...
            'Incomplete Pc/Kr/porosity coverage for %s case %02d, %s.', ...
            geologyId, caseId, windowName);

        selected = selectionCase(selectionCase.Window == windowName, :);
        assert(height(selected) == 1, ...
            'ReservoirReady:SelectionCount', ...
            'Expected one Swi-medoid selection for %s case %02d, %s.', ...
            geologyId, caseId, windowName);
        representativeRows = unique(krCase.RepresentativeKrReplaySourceRow( ...
            krCase.Window == windowName));
        assert(isscalar(representativeRows) && ...
            representativeRows == selected.SelectedReplaySourceRow(1), ...
            'ReservoirReady:RepresentativeMismatch', ...
            'Kr representative does not match the Swi medoid for %s case %02d, %s.', ...
            geologyId, caseId, windowName);
        selectedPcRows = pcCase(pcCase.Window == windowName & ...
            pcCase.ReplaySourceRow == selected.SelectedReplaySourceRow(1), :);
        assert(~isempty(selectedPcRows), ...
            'ReservoirReady:SelectedPcMissing', ...
            'Selected Swi-medoid Pc realization is missing for %s case %02d, %s.', ...
            geologyId, caseId, windowName);
        selectedPcSwi = uniqueNumericScalar(selectedPcRows.EffectiveSwi, ...
            'selected Pc EffectiveSwi');
        selectedTableSwi = uniqueNumericScalar(selected.SelectedEffectiveSwi, ...
            'selected table EffectiveSwi');
        assert(abs(selectedPcSwi - selectedTableSwi) <= ...
            opt.EndpointTolerance, 'ReservoirReady:SelectedSwiMismatch', ...
            'Selected Swi does not match its Pc curve for %s case %02d, %s.', ...
            geologyId, caseId, windowName);

        for s = 1:nSlices
            sliceId = referenceSlices(s);
            P = pcCase(pcCase.Window == windowName & ...
                pcCase.SliceIndex == sliceId, :);
            K = krCase(krCase.Window == windowName & ...
                krCase.SliceIndex == sliceId, :);
            Phi = porosityCase(porosityCase.Window == windowName & ...
                porosityCase.SliceIndex == sliceId, :);
            assert(~isempty(P) && ~isempty(K) && height(Phi) == 1, ...
                'ReservoirReady:MissingCurve', ...
                ['Missing Pc/Kr data or nonunique porosity for %s case ', ...
                 '%02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);

            P = sortrows(P, 'GasSaturation');
            K = sortrows(K, 'NormalizedSg');
            pcSg = numericColumn(P.GasSaturation);
            pcBar = numericColumn(P.PcBar);
            krSg = numericColumn(K.GasSaturation);
            krSw = numericColumn(K.WaterSaturation);
            krg = numericColumn(K.Krg);
            krw = numericColumn(K.Krw);
            pcReplaySource = uniqueNumericScalar(P.ReplaySourceRow, ...
                'Pc replay source row');
            krPcReplaySource = uniqueNumericScalar(K.PcReplaySourceRow, ...
                'Kr Pc replay source row');
            assert(pcReplaySource == krPcReplaySource, ...
                'ReservoirReady:ReplaySourceMismatch', ...
                'Pc/Kr replay source differs for %s case %02d, %s, slice %d.', ...
                geologyId, caseId, windowName, sliceId);
            porosityReplaySource = uniqueNumericScalar( ...
                Phi.ReplaySourceRow, 'porosity replay source row');
            assert(pcReplaySource == porosityReplaySource, ...
                'ReservoirReady:PorosityReplaySourceMismatch', ...
                ['Pc and porosity replay sources differ for %s case ', ...
                 '%02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);

            phiValue = uniqueNumericScalar(Phi.UpscaledPorosity, ...
                'upscaled porosity');
            poreVolume = uniqueNumericScalar(Phi.PoreVolume, 'pore volume');
            bulkVolume = uniqueNumericScalar(Phi.BulkVolume, 'bulk volume');
            assert(bulkVolume > 0 && phiValue >= 0 && phiValue <= 1, ...
                'ReservoirReady:PorosityBounds', ...
                ['Upscaled porosity or bulk volume is nonphysical for ', ...
                 '%s case %02d, %s, slice %d.'], ...
                geologyId, caseId, windowName, sliceId);
            porosityIdentityMismatch = abs(phiValue - ...
                poreVolume ./ bulkVolume);
            maxPorosityIdentityMismatch = max( ...
                maxPorosityIdentityMismatch, porosityIdentityMismatch);
            assert(porosityIdentityMismatch <= opt.PorosityTolerance, ...
                'ReservoirReady:PorosityIdentityMismatch', ...
                ['Upscaled porosity differs from pore-volume/bulk-volume ', ...
                 'by %.3g for %s case %02d, %s, slice %d.'], ...
                porosityIdentityMismatch, geologyId, caseId, ...
                windowName, sliceId);
            upscaledPorosity(w, s) = phiValue;
            bulkSgMaxPc = uniqueNumericScalar(P.BulkSgMax, ...
                'Pc BulkSgMax');
            effectiveSwiPc = uniqueNumericScalar(P.EffectiveSwi, ...
                'Pc EffectiveSwi');
            bulkSgMaxKr = uniqueNumericScalar(K.BulkSgMax, ...
                'Kr BulkSgMax');
            effectiveSwiKr = uniqueNumericScalar(K.EffectiveSwi, ...
                'Kr EffectiveSwi');

            endpointMismatch = max([ ...
                abs(bulkSgMaxPc - bulkSgMaxKr), ...
                abs(effectiveSwiPc - effectiveSwiKr), ...
                abs((1.0 - bulkSgMaxPc) - effectiveSwiPc), ...
                abs(max(pcSg) - bulkSgMaxPc), ...
                abs(max(krSg) - bulkSgMaxPc), ...
                max(abs(krSw - (1.0 - krSg)))]);
            maxEndpointMismatch = max(maxEndpointMismatch, endpointMismatch);
            assert(endpointMismatch <= opt.EndpointTolerance, ...
                'ReservoirReady:EndpointMismatch', ...
                ['Pc/Kr endpoint mismatch %.3g exceeds tolerance %.3g for ', ...
                 '%s case %02d, %s, slice %d.'], ...
                endpointMismatch, opt.EndpointTolerance, geologyId, ...
                caseId, windowName, sliceId);

            pcDrop = maximumDrop(pcBar);
            krgDrop = maximumDrop(krg);
            krwRise = maximumRise(krw);
            maxPcMonotonicDrop = max(maxPcMonotonicDrop, pcDrop);
            maxKrgMonotonicDrop = max(maxKrgMonotonicDrop, krgDrop);
            maxKrwMonotonicRise = max(maxKrwMonotonicRise, krwRise);
            assert(pcDrop <= opt.MonotonicTolerance, ...
                'ReservoirReady:NonmonotonicPc', ...
                'Pc is nonmonotonic for %s case %02d, %s, slice %d.', ...
                geologyId, caseId, windowName, sliceId);
            assert(krgDrop <= opt.MonotonicTolerance && ...
                krwRise <= opt.MonotonicTolerance, ...
                'ReservoirReady:NonmonotonicKr', ...
                'Kr is nonmonotonic for %s case %02d, %s, slice %d.', ...
                geologyId, caseId, windowName, sliceId);
            assert(all(krg >= -opt.MonotonicTolerance & ...
                krg <= 1 + opt.MonotonicTolerance) && ...
                all(krw >= -opt.MonotonicTolerance & ...
                krw <= 1 + opt.MonotonicTolerance), ...
                'ReservoirReady:KrBounds', ...
                'Kr lies outside [0,1] for %s case %02d, %s, slice %d.', ...
                geologyId, caseId, windowName, sliceId);

            pcCurves{w, s} = struct( ...
                'gasSaturation', pcSg, ...
                'pcBar', pcBar, ...
                'bulkSgMax', bulkSgMaxPc, ...
                'effectiveSwi', effectiveSwiPc, ...
                'replaySourceRow', pcReplaySource, ...
                'upscaledPorosity', phiValue);
            krCurves{w, s} = struct( ...
                'gasSaturation', krSg, ...
                'waterSaturation', krSw, ...
                'krg', krg, ...
                'krw', krw, ...
                'bulkSgMax', bulkSgMaxKr, ...
                'effectiveSwi', effectiveSwiKr, ...
                'shapeId', string(K.ShapeId(1)), ...
                'representativeReplaySourceRow', representativeRows);
        end
    end

    reservoirReady = struct();
    reservoirReady.schemaVersion = "1.1";
    reservoirReady.geologyId = geologyId;
    reservoirReady.level3CaseId = caseId;
    reservoirReady.level3CaseName = string(pcCase.Level3CaseName(1));
    reservoirReady.windowLabels = windows;
    reservoirReady.sliceIndices = referenceSlices;
    reservoirReady.pcCurves = pcCurves;
    reservoirReady.krCurves = krCurves;
    reservoirReady.upscaledPorosity = upscaledPorosity;
    reservoirReady.swiMedoidSelection = selectionCase;
    reservoirReady.provenance = struct( ...
        'pcNativeSource', pcSource, ...
        'krSliceSource', krSource, ...
        'selectionSource', selectionSource, ...
        'porositySource', porositySource, ...
        'createdAt', string(datetime('now', 'TimeZone', 'UTC')));

    matFile = fullfile(outputDir, sprintf( ...
        'reservoir_ready_%s_case%02d.mat', geologyId, caseId));
    save(matFile, 'reservoirReady', '-v7.3');
    matFiles(c) = string(matFile);
    qaRows(c, :) = {geologyId, caseId, ...
        string(pcCase.Level3CaseName(1)), nWindows, nSlices, ...
        nWindows * nSlices, nWindows * nSlices, numel(upscaledPorosity), ...
        height(selectionCase), min(upscaledPorosity, [], 'all'), ...
        max(upscaledPorosity, [], 'all'), maxPorosityIdentityMismatch, ...
        maxEndpointMismatch, maxPcMonotonicDrop, ...
        maxKrgMonotonicDrop, maxKrwMonotonicRise, true, string(matFile)};
end

qa = cell2table(qaRows, 'VariableNames', { ...
    'GeologyId', 'Level3CaseId', 'Level3CaseName', 'WindowCount', ...
    'SliceCount', 'PcCurveCount', 'KrCurveCount', ...
    'PorosityCount', 'SwiMedoidSelectionCount', ...
    'MinUpscaledPorosity', 'MaxUpscaledPorosity', ...
    'MaxPorosityIdentityMismatch', 'MaxEndpointMismatch', ...
    'MaxPcMonotonicDrop', 'MaxKrgMonotonicDrop', ...
    'MaxKrwMonotonicRise', 'Passed', 'MatFile'});
qaFile = fullfile(outputDir, 'reservoir_ready_qa_summary.csv');
writetable(qa, qaFile);

outputs = struct('matFiles', matFiles, 'qaTable', qa, ...
    'qaCsv', string(qaFile));
fprintf('Saved %d reservoir-ready MAT file(s): %s\n', ...
    numel(matFiles), outputDir);
fprintf('Saved reservoir-ready QA summary: %s\n', qaFile);
end


function [T, source] = loadInputTable(value, label)
% Read a table input or return an existing table unchanged.

if istable(value)
    T = value;
    source = "in-memory " + string(label) + " table";
else
    file = string(value);
    assert(isscalar(file) && isfile(file), ...
        'ReservoirReady:MissingInput', '%s input not found: %s', label, file);
    T = readtable(file, 'TextType', 'string');
    source = file;
end
end


function T = normalizeKeyColumns(T)
% Normalize shared case keys to stable string/numeric types.

T.GeologyId = string(T.GeologyId);
T.Level3CaseId = numericColumn(T.Level3CaseId);
T.Level3CaseName = string(T.Level3CaseName);
T.Window = string(T.Window);
if ismember('SliceIndex', T.Properties.VariableNames)
    T.SliceIndex = numericColumn(T.SliceIndex);
end
end


function requireColumns(T, required)
% Require all named columns in a table.

missing = setdiff(required, T.Properties.VariableNames);
assert(isempty(missing), 'ReservoirReady:MissingColumns', ...
    'Input table is missing columns: %s', strjoin(missing, ', '));
end


function values = numericColumn(values)
% Convert a table variable to a double column.

if ~isnumeric(values)
    values = str2double(string(values));
end
values = double(values(:));
assert(all(isfinite(values)), 'ReservoirReady:NonfiniteColumn', ...
    'Expected a finite numeric column.');
end


function value = uniqueNumericScalar(values, label)
% Return one repeated numeric metadata value.

values = numericColumn(values);
value = values(1);
tolerance = 1.0e-12 * max(1, abs(value));
assert(all(abs(values - value) <= tolerance), ...
    'ReservoirReady:InconsistentMetadata', ...
    '%s is inconsistent within one curve.', label);
end


function windows = orderedWindows(values)
% Return unique window labels ordered by their numeric suffix.

windows = unique(string(values), 'stable');
numbers = arrayfun(@windowNumber, windows);
[~, order] = sort(numbers);
windows = windows(order);
end


function value = windowNumber(label)
% Return the numeric suffix from a label such as famp6.

token = regexp(char(label), '(\d+)$', 'tokens', 'once');
assert(~isempty(token), 'ReservoirReady:WindowLabel', ...
    'Window label lacks a numeric suffix: %s', label);
value = str2double(token{1});
end


function value = maximumDrop(values)
% Return the largest decrease between adjacent values.

if numel(values) < 2
    value = 0;
else
    value = max([0; -diff(values(:))]);
end
end


function value = maximumRise(values)
% Return the largest increase between adjacent values.

if numel(values) < 2
    value = 0;
else
    value = max([0; diff(values(:))]);
end
end


function ensureFolder(folderPath)
% Create a folder when it does not exist.

if ~isfolder(folderPath)
    mkdir(folderPath);
end
end
