function [SATNUM, pcRegionCurves, krRegionCurves, regionTable] = ...
        get_reservoir_saturation_regions(reservoirReady)
%GET_RESERVOIR_SATURATION_REGIONS Read explicit downstream region inputs.
%
%   [SATNUM, PCCURVES, KRCURVES, REGIONTABLE] =
%   GET_RESERVOIR_SATURATION_REGIONS(RESERVOIRREADY) returns the global
%   window-by-slice SATNUM map and exactly one Pc/Kr curve per global
%   saturation region. No clustering or region detection is performed by
%   this accessor; all mappings must already be explicit in the MAT file.

assert(isfield(reservoirReady, 'saturationRegions'), ...
    'SaturationRegions:MissingMetadata', ...
    'reservoirReady does not contain explicit saturationRegions metadata.');
regions = reservoirReady.saturationRegions;
required = {'SATNUM', 'regionCount', 'regionCurveLinearIndices', ...
    'regionTable'};
for i = 1:numel(required)
    assert(isfield(regions, required{i}), ...
        'SaturationRegions:MissingMetadataField', ...
        'saturationRegions is missing %s.', required{i});
end

SATNUM = regions.SATNUM;
indices = double(regions.regionCurveLinearIndices(:));
assert(numel(indices) == double(regions.regionCount) && ...
    all(indices >= 1 & indices <= numel(reservoirReady.pcCurves)), ...
    'SaturationRegions:CurveLookup', ...
    'Region curve lookup indices are incomplete or out of range.');
pcRegionCurves = reservoirReady.pcCurves(indices);
krRegionCurves = reservoirReady.krCurves(indices);
regionTable = regions.regionTable;

assert(max(double(SATNUM(:))) == numel(pcRegionCurves) && ...
    height(regionTable) == numel(pcRegionCurves), ...
    'SaturationRegions:RegionCount', ...
    'SATNUM, region curves, and regionTable have inconsistent counts.');
end
