function contextCsv = prepare_production_replay_batch( ...
        selectionCsv, outputRoot, dataRoot, predictCodeRoot, mrstRoot, ...
        verifyToleranceLog10)
%PREPARE_PRODUCTION_REPLAY_BATCH Replay an arbitrary production task batch.
%
% CONTEXTCSV = PREPARE_PRODUCTION_REPLAY_BATCH(SELECTIONCSV, OUTPUTROOT,
% DATAROOT, PREDICTCODEROOT, MRSTROOT, TOLERANCE) replays every unique
% PREDICT realization in either a checkpoint-centered selection table or a
% six-window representative selection table. It enforces exact stochastic
% identity plus validated numerical equivalence of permeability, then writes
% the context table consumed by the unchanged Pc/Kr drivers.
%
% Fine-scale replay MAT files are intentionally written beneath OUTPUTROOT.
% The Engaging checkpoint worker deletes that temporary directory only after
% compact Pc products and provenance have been validated and published.

arguments
    selectionCsv (1, 1) string
    outputRoot (1, 1) string
    dataRoot (1, 1) string
    predictCodeRoot (1, 1) string
    mrstRoot (1, 1) string
    verifyToleranceLog10 (1, 1) double {mustBePositive} = 0.005
end

selectionCsv = absolutePath(selectionCsv);
outputRoot = absolutePath(outputRoot);
dataRoot = absolutePath(dataRoot);
predictCodeRoot = absolutePath(predictCodeRoot);
mrstRoot = absolutePath(mrstRoot);

assert(exist(selectionCsv, 'file') == 2, ...
    'ProductionReplay:MissingSelection', ...
    'Missing checkpoint selection CSV: %s', selectionCsv);
assert(exist(dataRoot, 'dir') == 7, ...
    'ProductionReplay:MissingDataRoot', ...
    'Missing frozen PREDICT input root: %s', dataRoot);
assert(exist(predictCodeRoot, 'dir') == 7, ...
    'ProductionReplay:MissingCodeRoot', ...
    'Missing frozen PREDICT code root: %s', predictCodeRoot);

thisDir = fileparts(mfilename('fullpath'));
examplesDir = fileparts(thisDir);
addpath(examplesDir, '-begin');
frozenExamplesDir = fullfile(predictCodeRoot, 'examples');
assert(exist(frozenExamplesDir, 'dir') == 7, ...
    'ProductionReplay:MissingFrozenExamples', ...
    'Frozen PREDICT examples folder not found: %s', frozenExamplesDir);
% Resolve the replay implementation from the frozen physics commit while
% retaining this production-only orchestration function from the live repo.
addpath(frozenExamplesDir, '-begin');
setupMrst(mrstRoot);

selection = readtable(selectionCsv, 'TextType', 'string');
required = {'task_id', 'task_key_sha256', 'geology_id', ...
    'scenario_index', 'scenario_label', 'scenario_name', 'case_index', ...
    'case_label', 'faulting_depth_m', 'sand_vcl', 'clay_vcl', ...
    'case_id', 'case_name', 'case_category', 'window', 'slice_index', ...
    'assigned_state', 'sampling_mode', 'sampling_pool', ...
    'selected_sample_index', 'exact_replay_seed', ...
    'source_checkpoint_file', 'source_seed_base', ...
    'source_num_attempts', 'source_num_rejected', ...
    'log_kxx', 'log_kyy', 'log_kzz'};
requireColumns(selection, required, 'checkpoint selection');
assert(height(selection) > 0, ...
    'ProductionReplay:EmptySelection', 'Checkpoint selection is empty.');
assert(numel(unique(selection.task_id)) == height(selection), ...
    'ProductionReplay:DuplicateTask', ...
    'Checkpoint selection contains duplicate task IDs.');
assert(numel(unique(selection.geology_id)) == 1, ...
    'ProductionReplay:MixedGeology', ...
    'One checkpoint batch must contain exactly one geology.');
windowNames = lower(string(selection.window));
uniqueWindows = unique(windowNames);
expectedWindows = "famp" + (1:6)';
isCheckpointBatch = numel(uniqueWindows) == 1;
isRepresentativeBatch = height(selection) == 6 && ...
    isequal(sort(uniqueWindows), expectedWindows) && ...
    all(groupcounts(categorical(windowNames)) == 1);
assert(isCheckpointBatch || isRepresentativeBatch, ...
    'ProductionReplay:InvalidWindowCoverage', ...
    ['A production replay batch must contain either one checkpoint window ', ...
     'or exactly one representative from each of famp1-famp6.']);
assert(numel(unique(str2double(selection.case_id))) == 1, ...
    'ProductionReplay:MixedLevel3Case', ...
    'One production replay batch must contain exactly one Level-3 case ID.');

replayDir = fullfile(outputRoot, 'replay_unique');
tableDir = fullfile(outputRoot, 'tables');
ensureFolder(replayDir);
ensureFolder(tableDir);

if isCheckpointBatch
    batchLabel = "checkpoint-centered";
    windowLabel = uniqueWindows;
else
    batchLabel = "six-window representative";
    windowLabel = strjoin(sort(uniqueWindows), ',');
end
fprintf('\n=== Replay %s production batch ===\n', batchLabel);
fprintf('Selection: %s\n', selectionCsv);
fprintf('Tasks: %d | geology: %s | window: %s\n', ...
    height(selection), selection.geology_id(1), windowLabel);

summary = replay_selected_predict_realizations( ...
    selectionCsv, replayDir, ...
    'DataRoot', dataRoot, ...
    'PredictCodeRoot', predictCodeRoot, ...
    'SmearOverlapRule', 'cell_union_psmear', ...
    'CollapseAdjacentLithology', true, ...
    'VerifyToleranceLog10', verifyToleranceLog10, ...
    'RequireDirectReplay', true);

assert(height(summary) == height(selection), ...
    'ProductionReplay:Incomplete', ...
    'Expected %d replay rows, found %d.', ...
    height(selection), height(summary));
requireColumns(summary, ...
    {'SourceRow', 'SelectedSampleIndex', 'ReplaySeed', 'AttemptIndex', ...
     'ReplayMode', 'VerificationStatus', 'MaxAbsLog10Diff', 'OutputFile'}, ...
    'replay summary');
summary.OutputFile = strtrim(string(summary.OutputFile));
missingOutput = ismissing(summary.OutputFile) | summary.OutputFile == "";
assert(~any(missingOutput), 'ProductionReplay:MissingOutputFile', ...
    'Replay summary contains %d empty output-file paths.', sum(missingOutput));
outputExists = arrayfun(@(pathValue) ...
    exist(char(pathValue), 'file') == 2, summary.OutputFile);
assert(all(outputExists), 'ProductionReplay:MissingOutputFile', ...
    'Replay summary contains %d output files that do not exist.', ...
    sum(~outputExists));
sourceRows = numericColumn(summary.SourceRow);
assert(isequal(sort(sourceRows), (1:height(selection))'), ...
    'ProductionReplay:SourceRows', ...
    'Replay SourceRow values do not cover the selection exactly once.');
selection = selection(sourceRows, :);

% Permeability uses a validated numerical-equivalence tolerance, but source
% realization identity remains exact. The selected row, accepted RNG seed,
% accepted attempt index, and deterministic discrete architecture may not be
% relaxed by the permeability tolerance.
actualSelectedIndex = exactIntegerColumn( ...
    summary.SelectedSampleIndex, 'replay selected-sample index');
expectedSelectedIndex = exactIntegerColumn( ...
    selection.selected_sample_index, 'frozen selected-sample index');
actualReplaySeed = exactIntegerColumn(summary.ReplaySeed, 'replay seed');
expectedReplaySeed = exactIntegerColumn( ...
    selection.exact_replay_seed, 'frozen exact replay seed');
actualAttemptIndex = exactIntegerColumn( ...
    summary.AttemptIndex, 'replay attempt index');
sourceSeedBase = exactIntegerColumn( ...
    selection.source_seed_base, 'checkpoint seed base');
[sourceAcceptedSeed, sourceAcceptedAttemptIndex] = ...
    readCheckpointAcceptedIdentity(selection, dataRoot);
assert(all(actualSelectedIndex == expectedSelectedIndex), ...
    'ProductionReplay:SelectedIndexMismatch', ...
    'Replay selected-sample index does not exactly match the frozen selection.');
assert(all(actualReplaySeed == expectedReplaySeed) && ...
       all(actualReplaySeed == sourceAcceptedSeed), ...
    'ProductionReplay:SeedMismatch', ...
    ['Replay RNG seed does not exactly match both the frozen selection and ', ...
     'the checkpoint-recorded accepted seed.']);
assert(all(actualAttemptIndex == sourceAcceptedAttemptIndex), ...
    'ProductionReplay:AttemptIndexMismatch', ...
    ['Replay attempt index does not exactly match the checkpoint-recorded ', ...
     'accepted attempt index.']);
assert(all(actualAttemptIndex == actualReplaySeed - sourceSeedBase + 1), ...
    'ProductionReplay:SeedAttemptMismatch', ...
    'Replay seed and attempt index are inconsistent with the checkpoint seed base.');
assert(all(startsWith(string(summary.ReplayMode), "direct_seed_")), ...
    'ProductionReplay:IndirectReplay', ...
    'Production replay must use a checkpoint-recorded direct seed.');
architectureHashes = replayArchitectureHashes(summary.OutputFile);
validArchitectureHash = arrayfun( ...
    @(value) ~isempty(regexp(char(value), '^[0-9a-f]{64}$', 'once')), ...
    architectureHashes);
assert(all(validArchitectureHash), ...
    'ProductionReplay:ArchitectureHash', ...
    'Every replay must record a canonical SHA-256 of its discrete material map.');
summary.SourceAcceptedSeed = sourceAcceptedSeed;
summary.SourceAcceptedAttemptIndex = sourceAcceptedAttemptIndex;
summary.DiscreteArchitectureStatus = ...
    repmat("matched", height(summary), 1);
summary.DiscreteArchitectureSha256 = architectureHashes;

status = string(summary.VerificationStatus);
maxDiff = numericColumn(summary.MaxAbsLog10Diff);
bad = status ~= "matched" | ~isfinite(maxDiff) | ...
    maxDiff > verifyToleranceLog10;
if any(bad)
    badRows = find(bad);
    for ibad = 1:numel(badRows)
        irow = badRows(ibad);
        details = load(char(summary.OutputFile(irow)), 'verification');
        verification = details.verification;
        fprintf(2, [ ...
            'Replay mismatch row=%d task=%s sample=%d seed=%d ', ...
            'status=%s max_abs_log10_diff=%.9g\n'], ...
            irow, selection.task_id(irow), ...
            numericColumn(selection.selected_sample_index(irow)), ...
            numericColumn(selection.exact_replay_seed(irow)), ...
            status(irow), maxDiff(irow));
        fprintf(2, ...
            '  reference_log10_k=[%.9g %.9g %.9g]\n', ...
            verification.ReferenceLog10PermMD);
        fprintf(2, ...
            '  replayed_log10_k=[%.9g %.9g %.9g]\n', ...
            verification.ReplayedLog10PermMD);
        fprintf(2, ...
            '  difference_log10_k=[%.9g %.9g %.9g]\n', ...
            verification.Log10Diff);
    end
    error('ProductionReplay:VerificationFailed', ...
        ['%d of %d checkpoint replay tasks failed numerical-equivalence ', ...
         'verification (tolerance %.3g log10 units).'], ...
        sum(bad), height(summary), verifyToleranceLog10);
end

summary.TaskId = selection.task_id;
summary.TaskKeySha256 = selection.task_key_sha256;
summary.GeologyId = selection.geology_id;
summary.ScenarioIndex = numericColumn(selection.scenario_index);
summary.ScenarioLabel = selection.scenario_label;
summary.ScenarioName = selection.scenario_name;
summary.CaseIndex = numericColumn(selection.case_index);
summary.CaseLabel = selection.case_label;
summary.FaultingDepthM = numericColumn(selection.faulting_depth_m);
summary.SandVcl = numericColumn(selection.sand_vcl);
summary.ClayVcl = numericColumn(selection.clay_vcl);
summary.Level3CaseId = numericColumn(selection.case_id);
summary.Level3CaseName = selection.case_name;
summary.CaseCategory = selection.case_category;
summary.Window = selection.window;
summary.SliceIndex = numericColumn(selection.slice_index);
summary.AssignedState = selection.assigned_state;
summary.SamplingMode = selection.sampling_mode;
summary.SamplingPool = selection.sampling_pool;
summary.LogKxx = numericColumn(selection.log_kxx);
summary.LogKyy = numericColumn(selection.log_kyy);
summary.LogKzz = numericColumn(selection.log_kzz);

contextCsv = fullfile(tableDir, 'replay_summary_context.csv');
writetable(summary, contextCsv);
fprintf('Verified %d/%d replay tasks; maximum log10(k) difference %.6g.\n', ...
    height(summary), height(summary), max(maxDiff));
fprintf('Saved production replay context: %s\n', contextCsv);
end


function setupMrst(mrstRoot)
% Initialize MRST modules required by exact PREDICT replay.

startupFile = fullfile(mrstRoot, 'startup.m');
assert(exist(startupFile, 'file') == 2, ...
    'ProductionReplay:MissingMrst', ...
    'MRST startup.m not found: %s', startupFile);
run(startupFile);
mrstModule add mrst-gui coarsegrid upscaling incomp mpfa mimetic ...
    deckformat ad-core ad-props ad-blackoil
mrstVerbose off
end


function requireColumns(T, required, label)
% Require all named columns in a table.

missing = setdiff(required, T.Properties.VariableNames);
assert(isempty(missing), 'ProductionReplay:MissingColumns', ...
    '%s is missing columns: %s', label, strjoin(missing, ', '));
end


function values = numericColumn(values)
% Convert a table variable to a finite numeric column.

if ~isnumeric(values)
    values = str2double(string(values));
end
values = double(values(:));
assert(all(isfinite(values)), 'ProductionReplay:NonfiniteColumn', ...
    'Expected a finite numeric column.');
end


function [acceptedSeeds, acceptedAttempts] = ...
        readCheckpointAcceptedIdentity(selection, dataRoot)
% Read the exact accepted seed and attempt for every selected source row.

selectedIndices = exactIntegerColumn( ...
    selection.selected_sample_index, 'selected_sample_index');
sourceCheckpointFiles = strtrim(string(selection.source_checkpoint_file));
assert(all(~ismissing(sourceCheckpointFiles) & sourceCheckpointFiles ~= ""), ...
    'ProductionReplay:MissingCheckpointPath', ...
    'Every selected realization must name its frozen source checkpoint.');

% Sampling tables retain the original source path as provenance. Resolve a
% platform-local copy from the frozen data root when that path was recorded
% on another operating system (for example, D:/... in an Engaging run).
checkpointFiles = strings(height(selection), 1);
for irow = 1:height(selection)
    sourceCheckpointFile = sourceCheckpointFiles(irow);
    if exist(char(sourceCheckpointFile), 'file') == 2
        checkpointFiles(irow) = sourceCheckpointFile;
    else
        checkpointFiles(irow) = fullfile(dataRoot, 'data', ...
            selection.scenario_label(irow), selection.window(irow), ...
            selection.case_label(irow), 'predict_runs.mat');
    end
end

acceptedSeeds = nan(height(selection), 1);
acceptedAttempts = nan(height(selection), 1);
[uniqueFiles, ~, fileGroup] = unique(checkpointFiles, 'stable');
for ifile = 1:numel(uniqueFiles)
    checkpointFile = char(uniqueFiles(ifile));
    assert(exist(checkpointFile, 'file') == 2, ...
        'ProductionReplay:MissingCheckpoint', ...
        'Frozen source checkpoint does not exist: %s', checkpointFile);
    checkpoint = load(checkpointFile, 'meta');
    assert(isfield(checkpoint, 'meta') && ...
           isfield(checkpoint.meta, 'AcceptedSeeds') && ...
           isfield(checkpoint.meta, 'AcceptedAttemptIndices'), ...
        'ProductionReplay:MissingCheckpointIdentity', ...
        ['Checkpoint %s must contain meta.AcceptedSeeds and ', ...
         'meta.AcceptedAttemptIndices.'], checkpointFile);

    rowIds = find(fileGroup == ifile);
    sourceSeeds = double(checkpoint.meta.AcceptedSeeds(:));
    sourceAttempts = double(checkpoint.meta.AcceptedAttemptIndices(:));
    sourceIndices = selectedIndices(rowIds);
    assert(all(sourceIndices >= 1 & ...
               sourceIndices <= numel(sourceSeeds) & ...
               sourceIndices <= numel(sourceAttempts)), ...
        'ProductionReplay:CheckpointRowOutOfRange', ...
        'A selected realization index is outside checkpoint %s.', checkpointFile);
    acceptedSeeds(rowIds) = sourceSeeds(sourceIndices);
    acceptedAttempts(rowIds) = sourceAttempts(sourceIndices);
end

acceptedSeeds = exactIntegerColumn(acceptedSeeds, 'checkpoint accepted seed');
acceptedAttempts = exactIntegerColumn( ...
    acceptedAttempts, 'checkpoint accepted attempt index');
end


function values = exactIntegerColumn(values, label)
% Convert a table variable to a finite exact-integer column.

values = numericColumn(values);
assert(all(values == round(values)), ...
    'ProductionReplay:NonintegerIdentity', ...
    '%s must contain exact integers.', label);
values = round(values);
end


function hashes = replayArchitectureHashes(outputFiles)
% Hash each reconstructed integer material map without changing replay data.

outputFiles = string(outputFiles);
hashes = strings(numel(outputFiles), 1);
for i = 1:numel(outputFiles)
    replayFile = char(outputFiles(i));
    replayData = load(replayFile, 'replay');
    assert(isfield(replayData, 'replay') && ...
           isfield(replayData.replay, 'Grid') && ...
           isstruct(replayData.replay.Grid) && ...
           isfield(replayData.replay.Grid, 'units'), ...
        'ProductionReplay:MissingArchitecture', ...
        'Replay file lacks replay.Grid.units: %s', replayFile);
    hashes(i) = discreteArchitectureSha256( ...
        replayData.replay.Grid.units);
end
end


function hashValue = discreteArchitectureSha256(units)
% Canonically hash dimensions and column-major integer material-unit IDs.

units = double(units);
assert(~isempty(units) && all(isfinite(units(:))) && ...
       all(units(:) == round(units(:))), ...
    'ProductionReplay:InvalidArchitecture', ...
    'Replayed Grid.units must be a nonempty finite integer map.');

digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(uint8('predict_discrete_architecture_grid_units_v1|'));
digest.update(uint8(sprintf('%d,', size(units))));
digest.update(uint8('|'));
flatUnits = int64(units(:));
chunkSize = 100000;
for first = 1:chunkSize:numel(flatUnits)
    last = min(first + chunkSize - 1, numel(flatUnits));
    digest.update(uint8(sprintf('%d,', flatUnits(first:last))));
end
bytes = typecast(digest.digest(), 'uint8');
hashValue = string(lower(reshape(dec2hex(bytes, 2).', 1, [])));
end


function pathValue = absolutePath(pathValue)
% Normalize an input path without requiring the destination to exist.

pathValue = string(java.io.File(char(pathValue)).getAbsolutePath());
end


function ensureFolder(folderPath)
% Create a folder if it does not already exist.

if exist(folderPath, 'dir') ~= 7
    mkdir(folderPath);
end
end
